events of yesterday
I have worked for the Darnley family since I was a boy. Colonel
Darnley was a very honest, decent gentleman. Last night I waited on
the guests at dinner. There was the family, Sir Redvers and Mr.
Coniston. Afterwards I served port to the gentlemen in the billiard
room. I had my own dinner at 9.30 with the other servants, then
cleaned boots. I was disturbed by a loud bang at 10.30. I thought it
was a door so did nothing about it. Shortly afterwards I went to bed
in the butlers' pantry and was woken by Mr. Coniston at 11.30. He
said that he had not been able to sleep and had gone to the lounge
to smoke. He saw a light under the study doors and was concerned
because the doors were locked and Colonel Darnley would not answer.
I offered to get my own keys but Mr. Coniston said it was too
urgent. As far as the study is concerned the Colonel kept the keys
on his person and I keep mine hidden - I won't say where - but you
can be sure no-one can get their on hand either. We left through the
kitchen door and I walked round to the french windows, Mr. Coniston
ran and was there a couple of seconds before me. He threw a stone
through the window and one of us, me I think put his hand through
the hole to open the lock. I can confirm that the window was locked.
We both went into the room and saw the Colonel's body with a bullet
through the chest. The body was on the floor and you couldn't tell
where the shot had come from. The Colonel's keys were in the locks
of the two doors.

alibi
I was with Mrs. Goodbody and young Norah in my pantry at both 10.30
and 11.30.

slippers
I believe these are Mr. Coniston's slippers. He was wearing them
when he woke me up to help the Colonel.

boots
The boots belong to Sir Redvers. They are - shall we say - on the
large side? He gave them to me yesterday afternoon and I cleaned
them after dinner. They were in the kitchen until I cleaned them. I
suppose they might have been taken afterwards. I don't think anyone
could have slipped past us servants to get to the kitchen through my
pantry. What puzzles me is : if a boot thief came in from the
outside door, what on earth was he wearing on his feet?

knife
I don't know anything about the knife.

cigarettes
I don't smoke. Colonel Darnley smoked cigars.

service revolver
It belongs to the master and was kept in the study. The study is
normally unlocked and it could have been removed at any time.

missing statue
Mr. Mellors told me that a tramp pitched it into the pond two days
ago.

gramophone
There is a gramophone in the morning room.

piano
There are two pianos, one in the music room and the other in the
morning room.

ladys shoes
I'm not sure. They may be Mrs. Sarah's or Miss Milicent's.

newspaper
I'm afraid I don't recognise it.

letter
I don't know anything about it.

handkerchief
I don't know anything about it.

colonel darnley
The master was extremely good to his family.

sarah darnley
I don't believe it is proper to speak of the family.

milicent darnley
I don't believe it is proper to speak of the family.

arthur coniston
I scarcely know the gentleman.

sir redvers slingsby
I've met the gentleman once or twice. A very hot-tempered man.

mildred goodbody
A fine woman. Honest as the day is long.

norah bagsby
A decent-enough girl. A little lazy.

ronald mellors
He's the gamekeeper. He seems honest enough.

flatfooted bootprints
I've studied all the people here and none of them are flat-footed.
It's a mystery ro me why the bootprints should be flat-footed.

hobnailed bootprints
I don't know whose these are.

slipper prints
I believe the slipper prints are Mr. Coniston's.

mens shoe prints
The shoe prints are mine.

womens shoe prints
I don't know whose these are.

cheroot in the pond
As far as I'm aware only the Colonel smoked cheroots. But he was a
most particular man and would never throw a butt into the pond.
