events yesterday murder
I was down for the weekend. It was no secret that I was going to ask
Colonel Darnley for permission to marry Millicent. I popped the question
to the old boy in the afternoon and he agreed. Last night we all had
dinner together and afterwards we fellows played a little billiards
before joining the ladies for coffee. At about 10.00 Sir Redvers broke
up the party by asking Darnley to go into the study with him. I asked
Millicent to come with me to the music room where we played duets for
half an hour.@
@
There was a noise. Millicent thought it was a poacher and hoped that
Mellors would catch him. She decided to go to bed. I stayed on to smoke
a cigar and didn't go up until 11.00. I noticed nothing odd except that
to get to my bedroom I had to go through the morning room where the
gramophone was playing a Chopin nocturne but there was no-one there.@
@
I undressed and went to bed but couldn't sleep. At about 11.30 I heard
a noise — a door banging, so I thought at the time. I decided to go
downstairs and smoke another cigar in the lounge. I noticed a light
under the study door and knocked on it to see who was there. I got
worried when it was locked and no-one answered so I got Billingsgate
and together we went outside and round to the French window. It was
locked too, so I picked a stone up and broke the glass. Billingsgate
stuck his hand through the hole and tried the lock. He told me it was
locked on the inside, and — damn me! — he was right. We both went
inside and found Darnley on the floor, shot and dead. When we checked
the doors to the hall and lounge we found the Colonel's keys in the
locks, so it would have been impossible to open them from the outside.
I had noticed some bootprints outside, so I went out and followed them.
They led around the house to the kitchen door. I followed in my slippers.

alibi
Millicent and I were together in the music room at 10.30. I don't
know how anyone can be expected to have an alibi for 11.30.
Certainly a single gentleman could never admit to one, if you follow
my meaning.

slippers
These are my slippers. I was wearing them when Billingsgate and I
broke into the study.

boots
I don't know anything about the boots.

knife
I don't know anything about the knife.

cigarettes
I smoke an expensive cigarette made by Fribourg & Treyer in London
- those and cigars after dinner, Cheroots same as old Darnley. I
would never smoke cheap cigarettes.

service revolver
I don't recognise it.

missing statue
I don't know what you're talking about.

gramophone
When I went to bed at 11.00, the gramophone was playing a Chopin
nocturne. Otherwise the morning room was empty. Later the record
appeared to be stuck. It was still playing when I went downstairs
shortly after 11.30.

piano
After dinner Millicent and I played duets on the piano in the music
room. Ah - now that I remember, there is also a piano in the morning
room, but on the couple of occasions I went into the room there was
no-one there, just a gramophone playing.

ladys shoes
I don't know whose shoes these are.

newspaper
I heard that old Slingsby had plunged into mining shares and needed
money urgently. Colonel Darnley mentioned it to me during our
conversation.

letter
I have no idea who old Darnley was writing to. I suppose it could
have been to old Slingsby. I fancy he had lost a lot of money and
needed a loan. We had spoken in the afternoon and Darnley had agreed
that I could marry Millicent.

handkerchief
I don't know whose handkerchief it is.

colonel darnley
A decent old buffer. When I asked his permission to marry Millicent
he agreed straight away. I was surprised, I admit it!

sarah
Very lively. I couldn't see old Darnley hanging on to her.

millicent
Be a gentleman, old fellow! Don't ask me to criticise my future
wife.

redvers slingsby
I scarcely know him but he seemed very angry with Darnley about
something. I got the feeling he had money troubles. A dangerous
fellow I should think.

arnold billingsgate
I barely know the chap.

mildred goodbody
I don't know the woman.

norah bagsby
I don't know the girl.

ronald mellors
I don't know the chap.

flatfooted bootprints
I followed the bootprints from the terrace around to the kitchen.

hobnailed bootprints
I don't know whose they are.

slipper prints
The prints from the slippers are mine.

mens shoe prints
I think they are probably Billingsgate's.

womens shoe prints
I don't know whose these are.

cheroot in the pond
I suppose it could be mine. I fancy I was smoking when Billingsgate
and I went outside. Maybe I did throw it in the pond. Does it
matter?

*
"Can't say I know anything about that. Sorry, old boy."
