LOC001_BATHROOM
The bathroom contains an enamelled cast iron bath with claw feet
and a toilet bearing a brass tablet calling it 'The Imperial Avenger'.
A washstand with a marble top and a pedestal washbowl complete
the ensemble. Various toileteries are scattered around in the normal
way.

LOC002_ORCHARD
The park wall lies north and has several pear-trees trained in
espalier against it. There are a large number of apple trees, but no
fruit. There are various marks on the ground, too unclear to be sure
that they are footprints.

LOC003_KITCHEN_GARDEN
The kitchen garden is full of frozen vegetables lying under snow.
Various footprints are visible in the snow.

LOC004_OUTHOUSES
This section of the garden contains various outhouses; a laundry, a
coal store and a pigeon-coop.

LOC005_ORNAMENTAL_POND
An ornamental pond stands at the western end of the terrace.
The pond is covered in ice. In the four corners of the pond are
stone pedestals. These hold statues.

LOC006_TERRACE
From the house a french window leads onto this paved terrace, which
shows traces of many footprints in the snow. The french window is
open and has a broken pane.

LOC007_COLONELS_STUDY
Colonel Darnley's body lies on a turkish carpet in the middle of the
study. A port glass is by his body and a tantalus of port stands on a
table. The room is panelled and contains several club-chairs, some
glass cases holding stuffed birds and a writing table with a letter on
it as well as various sporting magazines and a rack of sporting guns
and pistols. As you walk on the floor by the french window in the
west wall, you feel broken glass underfoot.

LOC008_HALL
The walls of the hall are decorated with swords and Civil War
armour. The floor is marble. The only furniture is a glass case
containing various flints and shards of pottery. At the far end of the
hall, two sets of fine armour stand either side of the stairs which
have barley-sugar bannisters and carved pineapple finials.

LOC009_KITCHEN
The kitchen has game birds hanging from the ceiling and the usual
kitchen furniture. On the sink draining-board is a knife. By the
outside door is a line of boots and some cleaning brushes and polish.

LOC010_BUTLERS_PANTRY
The butlers' pantry is laid out as a sitting room with a bed behind a
curtain. Two temporary beds have been made up. There is a small
bookshelf.

LOC011_MAZE
Situated on the east side of the house, the maze consists of low
box hedges. The marks in the snow cannot be deciphered into
footprints.

LOC012_WEST_WALK
The gravel path around the house passes between the smooth snow
covered tennis court and a bed of withered flowers covered in snow.
Various footprints are visible in the snow.

LOC013_LOUNGE
The centrepiece of the lounge is a three piece suite on a Chinese
carpet. There are several tables holding magazines and novels
marked with bookmarks. Recent family portraits are on the walls.
The fireplace is carved and holds the remains of a fire. On the
mantlepiece is an Indian rosewood box with an ivory inlay.

LOC014_DINING_ROOM
The dining room holds a fine oak table with chairs in William and
Mary style. A glass case contains various pieces of Delft pottery. A
sideboard holding a silver wine cooler and a pair of Sevres porcellain
urns stand against one wall. The fireplace is of carved marble and
the walls hold various Italian landscapes.

LOC015_MUSIC_ROOM
In the centre of the music room is a piano and, on top, a brass ashtray
with the stub of a cigar in it. There are several chairs, a music stand
and in one corner a large harp with broken strings.

LOC016_BILLIARD_ROOM
A full size table occupies the centre and of the wall a board indicates
the result of a game. There is a small bookcase holding magazines
and several novels by Conan Doyle and Buchan. On top of the book-
case are three wine glasses and an ashtray.

LOC017_DRIVE
From a pair of splendid wrought iron gates the drive runs north
ending in a flight of steps leading up to the principal entrance of the
house, flanked by a pair of stone lions. The snow reveals a mass of
footprints.

LOC018_EAST_WALK
This gravel path runs east-west across the front of the house flanked
by an avenue of statues. The snow covered gravel is too rough to
distinguish footprints.

LOC019_SUMMER_HOUSE
A wooden summer house stands on a patch of lawn. Inside can be
seen some croquet mallets and hoops, several cigarette ends and a
handkerchief.

LOC020_WEST_LAWN
Between the summer house and the drive is a lawn. It is planted with
a few saplings and the covering of snow shows footprints.

LOC021_STABLES
The stables are falling into disrepair. One part contains Colonel
Darnley's bay hunter. The other garages a large Daimler. The yard
is full of straw and oil spills, and is crossed by footprints. The tack
room holds the saddle and gear for the horse.

LOC022_EAST_LAWN
An area of lawn between the stables and the cottage. The smooth
covering of snow is broken by footprints.

LOC023_GAMEKEEPERS_COTTAGE
In the damp shade of some chestnut trees is a gamekeeper's cottage
tucked against the south-east corner of the park. The door of the
cottage is open and footprints are visible across the threshold. Inside
are various items of game, two shotguns on the wall, a table covered
by oil cloth, an unmade bed, a slop-stone sink and an open fire with a
pot hanging over it. The place is very dirty; the hearth is littered
with foodscraps, the ends of cigarettes and newspapers.

LOC024_MILICENT_BEDROOM
Milicent Darnley's bedroom is decorated to a young lady's taste
with a bed, wardrobe, dressing table and a small writing table.
The surfaces are covered with small ornaments, mainly of dogs
and the walls have pictures of favourite pets.

LOC025_LANDING
The landing walls hold some fine antlers and animal heads and some
bad portraits of the Darnley ancestors.

LOC026_SERVANTS_QUARTERS
The servants' quarters consist of a single room with two single beds,
a rail for hanging clothes on behind a curtain, a wash stand and a
chest of drawers. On the chest is a bundle of correspondence and
various framed photographs. A gentleman's country-suit with a
newspaper in the pocket is hanging on the rail amongst the dresses
and a pipe is on the washstand.

LOC027_MASTER_BEDROOM
Colonel and Mrs. Darnley's bedroom is heavily panelled and reflects
the Colonel's tastes, with sporting prints and a humidor of cigars.
There is a double bed, a dressing table, wardrobe and trouser press. A
small bathroom is attached.

LOC028_MORNING_ROOM
The morning room holds a chintz sofa and an occasional table with
magazines and books. Against one wall is a piano. On a table stands
a gramophone. There are various pictures, mainly watercolours of
birds.

LOC029_GUEST_ROOM
A guest-room decorated in blue with wardrobe, bed, washstand and
writing-table. By the bed is a pair of men's slippers. On the writing
table is a pack of cigarettes and some stationary and pens.

LOC030_GRAVEL_WALK
The gravel walk is covered by snow too broken to show the traces of
footprints.

LOC031_SOUTHEAST_CORNER
At the south-east corner of the house is a square of empty lawn. The
smooth cover of snow is broken by footprints.

PER101_COLONEL_DARNLEY
Aged 60. The Colonel served in the South African War and
contracted enteric fever which left him feeling debiliated and short-
tempered. He had only a small inheritance but made a fortune on the
stock exchange. He was free with his tips on the market, but didn't
always follow his own recommendations.

PER102_SARAH_DARNLEY
Colonel Darnley's wife. Aged 27. Fair-haired, beautiful and
sophisticated. She wears a morning dress and shows signs of tired-
ness and stress.

PER103_MILLICENT_DARNLEY
Colonel Darnley's daughter. Aged 23. Well-dressed but rather plain.
Cool and determined looking. She wears a blouse and skirt.

PER104_ARTHUR_CONISTON
Millicent Darnley's fiance. Aged 25. Average height and very good
looking. His manner is honest and friendly. He dresses fashionably
and wears black patent shoes.

PER105_SIR_REDVERS_SLINGSBY
Friend of the deceased. Aged 52. Very tall and boney with side
whiskers and a red face. Wears country-tweeds and boots. His
manner is ill-tempered.

PER106_ARNOLD_BILLINGSGATE
The Butler. Aged about 60; gentlemanly manners; bald and thin;
average height. Wears a tail coat and ordinary men's shoes.

PER107_MILDRED_GOODBODY
The Cook. Aged 55. Pleasant-faced. Cheerful. Overweight.

PER108_NORAH_BAGSBY
The Housemaid. Aged 19. Small pale girl who sniffs a lot. Wears a
maid's uniform.

PER109_RONALD_MELLORS
The Gamekeeper. Stocky, black curly hair, good looking, surly-
looking. Wears working clothes and hob-nailed boots. Age 35.

OBJ201_POND
Near the centre of the pond the ice is thinner as if it has frozen again
after having been broken. Beneath the ice you can see the missing
statue from the fourth pedestal.

OBJ202_SUNKEN_STATUE
The statue that is beneath the ice is the same as those on the
pedestals. Stuck in a crevice of the statue is the soaked butt of a
cheroot.

OBJ203_REVOLVER
The revolver found in the hall is a Webley-Fosbery .455 service
revolver. One bullet has been discharged from it.

OBJ204_STATUES
The statues form a set of four, representing the Four Seasons. They
are of Italian marble and rest on their own weight rather than being
cemented to their plinths. Some strength would be required to move
one.

OBJ205_FOOTPRINTS_POND
Only one set of footprints can be made out in the snow. They are of
flat footed bootprints coming to and from the terrace.

OBJ206_SLIPPERS
The slippers are slightly damp and stained with mud.

OBJ207_CIGARETTES
These cigarettes are an expensive brand by Tribourg & Freyer.

OBJ208_KNIFE
This kitchen knife is stained with blood.

OBJ209_BOOTS
All these boots are polished clean except for a mud stained pair that
apparently belong to Sir Redvers Slingsby.

OBJ212_FOOTPRINTS_KITCHEN_GARDEN
Both flat footed boot prints and slipper prints can be seen going
between the kitchen and the maze.

OBJ213_BED_MASTER
This double bed has not been slept in.

OBJ214_WARDROBE
As well as clothes the wardrobe contains a selection of
men's and women's shoes.

OBJ215_CIGARS
The cigars are Burmah cheroots.

OBJ216_DRESSING_TABLE
There is nothing of note on the dressing table.

OBJ217_SHOES
This selection of mens and womens shoes is unremarkable. One set of
lady's shoes is mud-stained.

OBJ219_CORRESPONDENCE
These letters are all from Mrs. Goodbody's nephew.

OBJ220_PHOTOGRAPHS
These photographs depict Mrs. Goodbody's various ugly relatives.

OBJ221_SUIT
This gentleman's country-suit is apparently Sir Redvers'.

OBJ222_NEWSPAPER
One headline on the front page catches your eye -
'Collapse of Rio Plata Mining Co. - Our co-respondent in Lima, Peru
reports the collapse of several silver mining companies through the
fraud of their directors. These frauds are expected to cause heavy
loss to British investors.'

OBJ223_PIPE
The pipe is in the style called 'calabash' with a meerschaum bowl and
amber mouthpiece.

OBJ224_BOOKSHELF
The bookshelf contains books on self-improvement and domestic
accounts.

OBJ225_FRENCH_WINDOW_TERRACE
One of the panes is smashed, but there is no glass on the terrace. The
window lock shows that it cannot be locked or unlocked from outside.

OBJ226_FOOTPRINTS_TERRACE
A mess of footprints including boots, slippers and some shoe prints.

OBJ227_BODY
The body is dressed in a smoking jacket open at the chest. There is a
bloody bullet wound in the front of his dress-shirt. The bullet has not
passed through the body. Evidently the Colonel had got out of his
chair on hearing or seeing his murderer. The impact of the bullet had
caused him to spin and fall and the furniture had got in the way,
further deflecting the body. It is no longer possible to tell the
direction of the shot.

OBJ228_PORT_GLASS
The port glass is one of a set engraved with the words 'Floreat
Darnley'. A crust of dried liquid is at the bottom and lip marks on the
rim though no trace of lipstick.

OBJ229_TANTALUS
The tantalus is made of cherrywood. It holds an empty decanter
with a silver label marked 'Brandy' and a half full decanter marked
'Port'. The decanters are normally inaccessible since they are held in
place by a sort of 'lid' of wood which is fastened by a small lock. The
key is in the lock.

OBJ230_LETTER
The letter is an incomplete draft : 'Dear Sir, I have considered your
monstrous suggestion and find I cannot....'

OBJ231_GUN_RACK
One of the pistols is missing from this rack.

OBJ232_FRENCH_WINDOW_STUDY
One pane is smashed. The glass on the floor is apparently from this.

OBJ233_SHATTERED_GLASS
This glass is apparently from the smashed French Window.

OBJ234_GRAMOPHONE
It has a device for playing several records in sequence. All the
records are Chopin.

OBJ235_PIANO_MORNING_ROOM
There are several sheets of Schubert Lied music on the piano's music
stand.

OBJ236_DISPLAY_CASE
According to a label at the front of the case these flints and shards of
pottery were found in the grounds of the house.

OBJ237_FOOTPRINTS_WEST
There are slipper prints, flat-footed boot prints and some shoe prints
heading to and from the terrace and the the front of the house.

OBJ238_CIGAR_STUB_MUSIC_ROOM
This cigar stub is a straight dark cylinder rather than the
conventional shape. That and the tarry appearance suggests a
cheroot.

OBJ239_PIANO_MUSIC_ROOM
The sheets of music on the piano are for duets.

OBJ240_WINE_GLASSES
The three wine glasses are all dirty.

OBJ241_ASHTRAY_BILLIARD_ROOM
The ashtray contains the remains of three cigars, one Havana and
two cheroots.

OBJ243_FOOTPRINTS_DRIVE
The prints from flat footed boots go east and west along the gravel
path in front of the house. Slipper prints come from the house and
head east and west along the path. Prints from men's shoes come
from the house and go west. Prints from lady's shoes head to and
from the frontdoor and the west lawn. At the gate end of the drive
the prints from men's hobnailed boots go between the west lawn and
the stables.

OBJ244_FOOTPRINTS_SOUTHEAST
The prints from flat footed boots and men's slippers are visible in the
snow heading around the corner of the house, to and from the maze
and avenue of statues.

OBJ245_CIGARETTE_ENDS_SH
These cigarette ends come from a cheap, mass produced brand.

OBJ246_HANDKERCHIEF
This is a lady's hanky, plain lace edged and perfumed.

OBJ247_FOOTPRINTS_WEST_LAWN
Prints from lady's shoes and men's hob-nailed boots can be seen in the
snow going between the drive and the summer house.

OBJ248_FOOTPRINTS_STABLES
The prints from hob-nailed boots can be seen in the snow going
between the drive and the east lawn.

OBJ249_FOOTPRINTS_EAST_LAWN
The prints from hob-nailed boots can be seen in the snow going east
to west between the stables and the cottage.

OBJ250_CIGARETTE_ENDS_COTTAGE
These cigarette ends come from a cheap, mass produced brand.

OBJ251_ARMOUR
A suit of Civil War three-quarter armour with a closed helmet.
Examination discovers a revolver concealed in the helmet.

OBJ252_DOOR_MAT
Some blurb about a damp doormat.

REC300_WHAT_REALLY_HAPPENED
On the morning of the murder Arthur Coniston, the boy-friend of
Milicent Darnley, arrived by arrangement to ask Colonel Darnley for
permission to marry his daughter. This conversation took place
during the afternoon and Colonel Darnley refused the request.
Although he found Coniston amusing, he felt that his visitor was
after Milicent's inheritance. Coniston, now resolved upon murder,
quietly informing the other members of the household that the
Colonel had agreed to tbe marriage. He was unaware that the Colonel
had decided to write him a letter confirming his rejection. During the
afternoon an unexpected visitor arrived, Sir Redvers Slingsby who
had invested in Peruvian mining shares on the advice of his friend
Colonel Darnley. In the morning's papers was news of the collapse of
these shares. Angry with his friend, Slingsby had rushed down to
Darnley Park to ask the Colonel to lend him money to avoid ruin.

Dinner that evening finished at 9.00. Milicent and Sarah retired
to the lounge for coffee while the men drank port and played
billiards. At nine 9.30 the gentlemen joined the ladies while the
servants ate in the kitchen. The atmosphere was tense since
Slingsby had not had opportunity to raise his problems. At 10.00 that
night impatience got the better of him and he drew Darnley to the
study whilst Coniston and Milicent went to the music room to sing
duets. For half an hour Slingsby and the Colonel quarelled (at this
time Billingsgate was cleaning boots in the kitchen) and at 10.30
Slingsby stormed out of the study by the hall door, slamming it
furiously. This noise was interpreted by some as a shot. The
slamming of the door underlined the generally tense atmosphere.
The ladies went upstairs but Arthur Coniston stayed in the music
room smoking a cheroot and considering his plan. He was unaware
that Sarah had plans of her own.

Sarah Darnley was unhappy with her husband and having an
affair with Mellors, the gamekeeper. She had arranged to meet
Mellors at the summer house at 10.45. Mellors was there, waiting and
smoking cigarettes. Sarah took steps to keep the affair secret and to
maintain to Milicent the pretence that she was in the house, she told
her of her intention to play on the morning room piano. In truth she
played a series of gramophone records which Milicent heard from her
room. It was not necessary for her to take account of Colonel Darnley
since experience had taught her that the Colonel would lock himself
in his study and get drunk on such an occasion as this. Sarah next
left the house and went down to the summer house where she met
Mellors.

Leaving the music room, Coniston tried the study door and finding
it locked, guessed what was happening and devised his plan. He had
stolen a gun from the study earlier in the day. He now changed into
dressing gown and slippers and went outside the house and around to
the kitchen door which was open. Reaching through the door he
picked up Sir Redvers Slingsby's boots. Changing into them he walked
around the house to the terrace. The boots being too large, they left
flat-footed bootprints. From the terrace Coniston looked into the
study where the Colonel was drinking. He tapped on the window, the
Colonel stood up and saw him, Coniston fired the gun and the Colonel
fell dead. He now had to act fast to dispose of the gun, disguise of the
fact of the bullet-hole in the window glass and return the boots. He
broke the ice on the pond with a statue taken from one of the
pedestals and threw the gun into the water. He then returned to the
kitchen, changed the boots for the slippers and then entered the
house by the front door. He did not notice Sarah who had heard the
shot and rushed back before everyone was roused by the noise and
she was discovered. In her haste Sarah dropped a handkerchief in
the summer house.

Coniston now came to the boldest part of his plot. He woke
Billingsgate and persuaded him to break in by the french window
instead of searching for his keys. Coniston took care to reach the
patio before his companion and threw a stone through the same pane
of glass that bore the bullet-hole from the fatal shot, thus
obliterating the evidence of from where the shooting took place. He
then invited Billingsgate to open the window and confirm that it had
been locked. He also told the Butler that he intended to follow the
murderer's bootprints which were clear in the snow. The object of
this move was to provide an explanation of the trail already left by
his slippers when he first stole and returned the boots.

Various minor clues led towards Coniston as the murderer, but one
was fatal to him. It was evident that the murderer had worn the
boots and returned them to the kitchen. How then had the murderer
left the kitchen in his/her own footwear? There were only two
possibilities : the murderer had left via the butlers' pantry or the
outside door. The former was impossible since three people were
occupying the pantry of whom at least one (Mrs. Goodbody) had been
wakened by the shot and would have heard any stranger entering the
room. The second was possible but the murderer would leave the foot-
prints of his ordinary footwear. Other than the boots, there were
prints only from Arthur Coniston's slippers. Coniston's explanation
that he had left these prints in following the murderers boot-trail
would not hold water. The murderer had to leave footprints in two
sets of footwear. Coniston's slippers were the only other set.

REC401_SEALED_ROOM_MURDER_INTRO
You have been summoned to Darnley Park one winter's day to
investigate the murder of Colonel Sebastian Darnley at some time
the previous evening.
The suspects are:
Sarah Darnley - the deceased's wife
Milicent Darnley - the deceased's daughter
Arthur Coniston - fiance of Milicent
Sir Redvers Slingsby - friend of the deceased
Arnold Billingsgate - butler
Mildred Goodbody - cook
Norah Bagsby - housemaid
Ronald Mellors - gamekeeper
You are free to search the house and grounds and to question the
suspects. Examination of the scene and skillful interrogation will
yield sufficient information to solve the mystery. And mystery it is!
The body of Colonel Darnley was found in his study, the doors and
window of which were all locked from the inside. The only keys were
in the possession of the Colonel and his faithful butler. How could
the sealed-room murder be comitted?

INT1001_SARAH_EVENTS_YESTERDAY
I married Sebastian two years ago. I am more than twenty years
younger than he - really not much older than Milicent. We have been
very happy together. Last night we all had dinner together. After-
wards the men played billiards while Milicent and I had coffee in the
lounge. At about 9.30 the men joined us for half an hour then Arthur
and Milicent said that they were going to the music room. Sebastian
and Sir Redvers had business to talk about so they went into the
study. I heard them quarelling but couldn't tell what about.
Next there was a loud noise which I took to be Sir Redvers leaving
the study by the door to the hall and banging the door. I stayed in
the lounge for ten minutes and then went upstairs where I ran into
Milicent on the landing. She said that she had left Arthur in the
billiard room and was going to bed. I went into the morning room and
played some Chopin nocturnes on the piano there until about 11.30
when I heard a noise like a shot which I thought was poachers.
Looking at my watch I decided it was time to go to bed. I was getting
changed when I heard Billingsgate rush upstairs to wake Sir Redvers.
Milicent heard the racket and came into my room from hers. And the
rest you know.

INT1003_SARAH_ALIBI
At 10.30 I was reading and drinking coffee in the lounge - on my
own, I'm afraid. At 11.30 I was playing the piano in the morning room
- also alone, alas! I don't suppose it looks to good?

INT1004_SARAH_SLIPPERS
I don't know whose slippers these are.

INT1005_SARAH_BOOTS
I don't know anything about them.

INT1006_SARAH_KNIFE
I don't know anything about the knife.

INT1007_SARAH_CIGARETTES
I can't imagine why you are asking me this question. Arthur
Coniston smokes cigarettes.

INT1008_SARAH_REVOLVER
I don't recognise it.

INT1009_SARAH_MISSING_STATUE
I believe a rather nasty tramp, who called two days ago threw it
into the pond.

INT1010_SARAH_GRAMOPHONE
The gramophone? I was in the morning room from about 10.40 until
11.30 playing the piano. It's possible I played a record, but I don't
remember doing so.

INT1011_SARAH_PIANO
If you mean the morning room piano, I was playing it from about
10.40 until I heard the bang at 11.30. I was on my own throughout
and no-one else came into the room.

INT1012_SARAH_LADYS_SHOES
Yes, these are my shoes, but I don't recall when I last wore them. I
have no idea why they should be damp - possibly I had them on
earlier yesterday.

INT1013_SARAH_NEWSPAPER
I believe that Sebastian advised one or two people to invest in
Peruvian shares.

INT1014_SARAH_LETTER
My husband said something to me about having to write a letter. I
understood it was for Arthur - or was it Sir Redvers? Afterwards
Arthur told me that Sebastian had agreed to the marriage, and
Redvers said that he and Sebastian had sorted out their business; so
I'm at a loss about the letter.

INT1015_SARAH_HANDKERCHIEF
You found it in the summer house? I'm absolutely sure it isn't mine.

INT1016_SARAH_ON_COLONEL_DARNLEY
He was somewhat strict and suspicous by nature, but we were happy
enough.

INT1018_SARAH_ON_MILICENT
Her father spoiled her so she got used to having her own way.
Sebastian probably agreed to Arthur Coniston's proposal for fear
of what Milicent would do if he refused. I can't see him crossing
Milicent on a matter like that.

INT1019_SARAH_ON_CONISTON
A charmer. I was suspicous of his motives for marrying Milicent, but
Arthur said that when he asked Sebastian my husband agreed, so I
am probably mistaken.

INT1020_SARAH_ON_SLINGSBY
I felt he had some sort of grudge against Sebastian.

INT1021_SARAH_ON_BILLINGSGATE
Very honest and loyal.

INT1022_SARAH_ON_GOODBODY
A gossip.

INT1023_SARAH_ON_BAGSBY
Lazy.

INT1024_SARAH_ON_MELLORS
A very loyal gamekeeper.

INT1025_SARAH_FLATFOOTED_BOOTPRINTS
I'm too distressed to talk about this.

INT1026_SARAH_HOBNAILED_BOOTPRINTS
I'm too distressed to talk about this.

INT1027_SARAH_SLIPPER_PRINTS
I'm too distressed to talk about this.

INT1028_SARAH_MENS_SHOE_PRINTS
I'm too distressed to talk about this.

INT1029_SARAH_WOMENS_SHOE_PRINTS
I'm too distressed to talk about this.

INT1030_SARAH_CHEROOT_IN_POND
I don't know anything about it.

INT1101_MILICENT_EVENTS_YESTERDAY
Father was a difficult man to live with but I never expected - this!
Last night we all ate together until coffee which Sarah and I took
together in the lounge. The men joined us later for half an hour,
then Arthur and I went into the music room where we talked for a
while and played duets on the piano. At about 10.30 I decided to go to
bed. I know the time because I looked at my watch when there was a
loud noise - probably a poacher somewhere. Arthur stayed in the
billiard room and I went upstairs.
I think I saw Sir Redvers disappearing into his bedroom, but I was
distracted by Sarah who was on the landing. She said she was
intending to play the piano in the morning room and hoped it would't
disturb me. I went to my room and stayed there. I heard Sarah
playing the piano then drifted off to sleep. I woke up at about 11.20
by the bedside clock and heard Sarah still playing a Chopin nocturne.
She seemed to be having trouble since the same part was being
repeated over and over again. I went to sleep for a few more minutes
when there was a bang - a door slamming, I thought. Then at about
midnight there was a racket of people everywhere. I went into
Sarah's room and found her undressing there. We went into the
morning room and found Billingsgate waking Sir Redvers.

INT1103_MILICENT_ALIBI
I was with Arthur in the music room at 10.30 and, naturally, I was
alone in bed at 11.30.

INT1104_MILICENT_SLIPPERS
I don't know whose slippers these are.

INT1105_MILICENT_BOOTS
I don't know anything about these boots.

INT1106_MILICENT_KNIFE
I don't know anything about the knife.

INT1107_MILICENT_CIGARETTES
I don't smoke. My father smoked cigars.

INT1108_MILICENT_REVOLVER
I don't recognise it.

INT1109_MILICENT_MISSING_STATUE
Someone - I forget who - told me that a beggar had pushed it into the
pond. Out of spite I suppose.

INT1110_MILICENT_GRAMOPHONE
We have a gramophone in the morning room.

INT1111_MILICENT_PIANO
Which piano? Arthur and I played duets on the music room piano for
a while after dinner. I remember that later, Sarah said she intended
to play the morning room piano. I woke up at about 11.20 and heard
Sarah still playing a Chopin nocturne. She was having difficulty
and repeated the same piece again and again.

INT1112_MILICENT_LADYS_SHOES
They aren't my shoes.

INT1113_MILICENT_NEWSPAPER
I don't read the newspaper frequently.

INT1114_MILICENT_LETTER
I don't know anything about this letter.

INT1115_MILICENT_HANDKERCHIEF
I'm always losing handkerchiefs so I suppose it could be mine. I don't
remember when I lose them. I certainly wasn't in the summer house
yesterday. Is it important?

INT1116_MILICENT_ON_COLONEL_DARNLEY
Daddy was a tyrant but always kind to me. He was always fearful
that Sarah would leaver him for a younger man.

INT1117_MILICENT_ON_SARAH
We got on well enough though it is difficult to have a step-mother
who is almost the same age. I thought she would leave daddy some
day as soon as she found a lover. But, of course, she would need
Daddy's money.

INT1119_MILICENT_ON_CONISTON
He's a darling! I don't know how he persuaded daddy to agree, so I
am probably mistaken.

INT1120_MILICENT_ON_SLINGSBY
I didn't know him before last night.

INT1121_MILICENT_ON_BILLINGSGATE
A decent old fellow.

INT1122_MILICENT_ON_GOODBODY
An old dear.

INT1123_MILICENT_ON_BAGSBY
A clumsy girl.

INT1124_MILICENT_ON_MELLORS
Furtive. I don't like the way he looks at my step-mother. I advised
Daddy to get rid of him.

INT1125_MILICENT_FLATFOOTED_BOOTPRINTS
Oh really, it's too silly to ask me to recognise footprints.

INT1126_MILICENT_HOBNAILED_BOOTPRINTS
Oh really, it's too silly to ask me to recognise footprints.

INT1127_MILICENT_SLIPPER_PRINTS
Oh really, it's too silly to ask me to recognise footprints.

INT1128_MILICENT_MENS_SHOE_PRINTS
Oh really, it's too silly to ask me to recognise footprints.

INT1129_MILICENT_WOMENS_SHOE_PRINTS
Oh really, it's too silly to ask me to recognise footprints.

INT1130_MILICENT_CHEROOT_IN_POND
I don't know anything about it.

INT1201_CONISTON_EVENTS_YESTERDAY
I was down for the weekend. It was no secret that I was going to
ask Colonel Darnley for permission to marry Milicent. I popped the
question to the old boy in the afternoon and he agreed. Last night we
all had dinner together and afterwards we fellows played a little
billiards before joining the ladies for coffee. At about 10.00 Sir
Redvers broke up the party by asking Darnley to go into the study
with him. I asked Milicent to come with me to the music room where
we played duets for half an hour. There was a noise. Milicent
thought it was a poacher and hoped that Mellor's would catch him.
She decided to go to bed. I stayed on to smoke a cigar and didn't go up
until 11.00. I noticed nothing odd except that to get to my bedroom I
had to go through the morning room where the gramophone was
playing a Chopin nocturne but there was no-one there. I undressed
and went to bed but couldn't sleep. At about 11.30 I heard a noise -
a door banging, so I thought at the time. I decided to go downstairs
and smoke another cigar in the lounge. I noticed a light under the
study door and knocked on it to see who was there. I got worried
when it was locked and no-one answered so I got Billingsgate and
together we went outside and round to the french window. It was
locked too, so I picked a stone up and broke the glass. Billingsgate
stuck his hand through the hole and tried the lock. He told me it was
locked on the inside, and - damn me! - he was right. We both went
inside and found Darnley on the floor, shot and dead. When we
checked the doors to the hall and lounge we found the Colonel's keys
in the locks, so it would have been impossible to open them from the
outside. I had noticed some bootprints outside, so I went out and
followed them. They led around the house to the kitchen door. I
followed in my slippers.

INT1203_CONISTON_ALIBI
Milicent and I were together in the music room at 10.30. I don't
know how anyone can be expected to have an alibi for 11.30.
Certainly a single gentleman could never admit to one, if you follow
my meaning.

INT1204_CONISTON_SLIPPERS
These are my slippers. I was wearing them when Billingsgate and I
broke into the study.

INT1205_CONISTON_BOOTS
I don't know anything about the boots.

INT1206_CONISTON_KNIFE
I don't know anything about the knife.

INT1207_CONISTON_CIGARETTES
I smoke and expensive cigarette made by Fribourg & Treyer in
London - those and cigars after dinner, Cheroots same as old Darnley.
I would never smoke cheap cigarettes.

INT1208_CONISTON_REVOLVER
I don't recognise it.

INT1209_CONISTON_MISSING_STATUE
I don't know what you're talking about.

INT1210_CONISTON_GRAMOPHONE
When I went to bed at 11.00, the gramophone was playing a Chopin
nocturne. Otherwise the morning room was empty. Later the record
appeared to be stuck. It was still playing when I went downstairs
shortly after 11.30.

INT1211_CONISTON_PIANO
After dinner Milicent and I played duets on the piano in the music
room. Ah - now that I remember, there is also a piano in the morning
room, but on the couple of occasions I went into the room there was
no-one there, just a gramophone playing.

INT1212_CONISTON_LADYS_SHOES
I don't know whose shoes these are.

INT1213_CONISTON_NEWSPAPER
I heard that old Slingsby had plunged into mining shares and needed
money urgently. Colonel Darnley mentioned it to me during our
conversation.

INT1214_CONISTON_LETTER
I have no idea who old Darnley was writing to. I suppose it could
have been to old Slingsby. I fancy he had lost a lot of money and
needed a loan. We had spoken in the afternoon and Darnley had
agreed that I could marry Milicent.

INT1215_CONISTON_HANDKERCHIEF
I don't know whose handkerchief it is.

INT1216_CONISTON_ON_COLONEL_DARNLEY
A decent old buffer. When I asked his permission to marry Milicent
he agreed straight away. I was suprised, I admit it!

INT1217_CONISTON_ON_SARAH
Very lively. I couldn't see old Darnley hanging on to her.

INT1218_CONISTON_ON_MILICENT
Be a gentleman, old fellow! Don't ask me to criticise my future wife.

INT1220_CONISTON_ON_SLINGSBY
I scarcely know him but he seemed very angry with Darnley about
something. I got the feeling he had money troubles. A dangerous
fellow I should think.

INT1221_CONISTON_ON_BILLINGSGATE
I barely know the chap.

INT1222_CONISTON_ON_GOODBODY
I don't know the woman.

INT1223_CONISTON_ON_BAGSBY
I don't know the girl.

INT1224_CONISTON_ON_MELLORS
I don't know the chap.

INT1225_CONISTON_FLATFOOTED_BOOTPRINTS
I followed the Bootprints from the terrace around to the kitchen.

INT1226_CONISTON_HOBNAILED_BOOTPRINTS
I don't know whose they are.

INT1227_CONISTON_SLIPPER_PRINTS
The prints from the slippers are mine.

INT1228_CONISTON_MENS_SHOE_PRINTS
I think they are probably Billingsgate's.

INT1229_CONISTON_WOMENS_SHOE_PRINTS
I don't know whose these are.

INT1230_CONISTON_CHEROOT_IN_POND
I suppose it could be mine. I fancy I was smoking when Billingsgate
and I went outside. Maybe I did throw it in the pond. Does it matter?

INT1301_SLINGSBY_EVENTS_YESTERDAY
I have known Darnley for about 20 years. It was some confidential
business dealings that brought me here urgently yesterday. Last
night I had dinner with the family and young Coniston.
Afterwards about 9.00 - we gentlemen had a game and some port
in the billiard room, then we joined the ladies in the lounge for half an
hour. Darnley and I left the others at 10.00 and chatted about our
business for a while. The discussion was very friendly and I left
Darnley alive at 10.30. I was sleeping in the servants quarters and
went to bed straight away. Having had a bit to drink I slept very
soundly and heard nothing until Billingsgate woke me at midnight to
tell me about this terrible business.

INT1303_SLINGSBY_ALIBI
I left Darnley alive at 10.30 and it's damn nonsense to suggest I
shot him with all the house awake and then waited to see what would
happen. At 11.30 I was asleep like a good Christian, and the Devil
take you if a fellow needs an alibi!

INT1304_SLINGSBY_SLIPPERS
I don't know whose slippers these are.

INT1305_SLINGSBY_BOOTS
These are certainly my boots. I last wore them yesterday afternoon
and put them out for Billingsgate to clean. I certainly didn't wear
them after dinner and can't explain who may have. I suppose that,
if the staff were asleep, someone could have sneaked into the
kitchen and taken them.

INT1306_SLINGSBY_KNIFE
I don't know anything about the knife.

INT1307_SLINGSBY_CIGARETTES
I smoke a pipe and the occasional Havana cigar. My pipe is in my
room.

INT1308_SLINGSBY_REVOLVER
I don't recognise it.

INT1309_SLINGSBY_MISSING_STATUE
I don't know what you're talking about.

INT1310_SLINGSBY_GRAMOPHONE
The Darnley's have a gramophone in the morning room.

INT1311_SLINGSBY_PIANO
The Darnley's have two pianos, one in the music room and one in the
morning room.

INT1312_SLINGSBY_LADYS_SHOES
I don't know whose shoes these are.

INT1313_SLINGSBY_NEWSPAPER
I was reading it on the train coming here. Some of my friends lost
money in the collapse.

INT1314_SLINGSBY_LETTER
The letter certainly wasn't addressed to me. Darnley would have
called me by name, not 'Dear Sir' - afterall we were friends.

INT1315_SLINGSBY_HANDKERCHIEF
I don't know whose handkerchief it is.

INT1316_SLINGSBY_ON_COLONEL_DARNLEY
A hard man but very fair. Once I had explained my business problem
he agreed to help me out.

INT1317_SLINGSBY_ON_SARAH
Darnley should never have married her.

INT1318_SLINGSBY_ON_MILICENT
A charming young lady. Spoiled by her father. Personally I shouldn't
like to get on her wrong side.

INT1319_SLINGSBY_ON_CONISTON
Last night was the first time I met him but he seemed a decent
fellow.

INT1321_SLINGSBY_ON_BILLINGSGATE
I barely know the man.

INT1322_SLINGSBY_ON_GOODBODY
I don't know the woman.

INT1323_SLINGSBY_ON_BAGSBY
I don't know the girl.

INT1324_SLINGSBY_ON_MELLORS
I don't know the man.

INT1325_SLINGSBY_FLATFOOTED_BOOTPRINTS
The bootprints around the house look like mine, but I didn't make
them. I'm not flat-footed.

INT1326_SLINGSBY_HOBNAILED_BOOTPRINTS
I don't know anything about them.

INT1327_SLINGSBY_SLIPPER_PRINTS
I don't know anything about them.

INT1328_SLINGSBY_MENS_SHOE_PRINTS
I don't know anything about them.

INT1329_SLINGSBY_WOMENS_SHOE_PRINTS
I don't know anything about them.

INT1330_SLINGSBY_CHEROOT_IN_POND
A cheroot? Not me, old man! I'm one for Havanas if I'm not smoking
the old pipe.

INT1401_BILLINGSGATE_EVENTS_YESTERDAY
I have worked for the Darnley family since I was a boy. Colonel
Darnley was a very honest, decent gentleman. Last night I waited on
the guests at dinner. There was the family, Sir Redvers and Mr.
Coniston. Afterwards I served port to the gentlemen in the billiard
room. I had my own dinner at 9.30 with the other servants, then
cleaned boots. I was disturbed by a loud bang at 10.30. I thought it
was a door so did nothing about it. Shortly afterwards I went to bed
in the butlers' pantry and was woken by Mr. Coniston at 11.30.
He said that he had not been able to sleep and had gone to the
lounge to smoke. He saw a light under the study doors and was
concerned because the doors were locked and Colonel Darnley would
not answer. I offered to get my own keys but Mr. Coniston said it was
too urgent. As far as the study is concerned the Colonel kept the
keys on his person and I keep mine hidden - I won't say where - but
you can be sure no-one can get their on hand either. We left through
the kitchen door and I walked round to the french windows, Mr.
Coniston ran and was there a couple of seconds before me. He threw
a stone through the window and one of us, me I think put his hand
through the hole to open the lock. I can confirm that the window
was locked. We both went into the room and saw the Colonel's body
with a bullet through the chest. The body was on the floor and you
couldn't tell where the shot had come from. The Colonel's keys were
in the locks of the two doors.

INT1403_BILLINGSGATE_ALIBI
I was with Mrs. Goodbody and young Norah in my pantry at both
10.30 and 11.30.

INT1404_BILLINGSGATE_SLIPPERS
I believe these are Mr. Coniston's slippers. He was wearing them
when he woke me up to help the Colonel.

INT1405_BILLINGSGATE_BOOTS
The boots belong to Sir Redvers. They are - shall we say - on the
large side? He gave them to me yesterday afternoon and I cleaned
them after dinner. They were in the kitchen until I cleaned them. I
suppose they might have been taken afterwards. I don't think
anyone could have slipped past us servants to get to the kitchen
through my pantry. What puzzles me is : if a boot thief came in from
the outside door, what on earth was he wearing on his feet?

INT1406_BILLINGSGATE_KNIFE
I don't know anything about the knife.

INT1407_BILLINGSGATE_CIGARETTES
I don't smoke. Colonel Darnley smoked cigars.

INT1408_BILLINGSGATE_REVOLVER
It belongs to the master and was kept in the study. The study is
normally unlocked and it could have been removed at any time.

INT1409_BILLINGSGATE_MISSING_STATUE
Mr. Mellors told me that a tramp pitched it into the pond two days
ago.

INT1410_BILLINGSGATE_GRAMOPHONE
There is a gramophone in the morning room.

INT1411_BILLINGSGATE_PIANO
There are two pianos, one in the music room and the other in the
morning room.

INT1412_BILLINGSGATE_LADYS_SHOES
I'm not sure. They may be Mrs. Sarah's or Miss Milicent's.

INT1413_BILLINGSGATE_NEWSPAPER
I'm afraid I don't recognise it.

INT1414_BILLINGSGATE_LETTER
I don't know anything about it.

INT1415_BILLINGSGATE_HANDKERCHIEF
I don't know anything about it.

INT1416_BILLINGSGATE_ON_COLONEL_DARNLEY
The master was extremely good to his family.

INT1417_BILLINGSGATE_ON_SARAH
I don't believe it is proper to speak of the family.

INT1418_BILLINGSGATE_ON_MILICENT
I don't believe it is proper to speak of the family.

INT1419_BILLINGSGATE_ON_CONISTON
I scarcely know the gentleman.

INT1420_BILLINGSGATE_ON_SLINGSBY
I've met the gentleman once or twice. A very hot-tempered man.

INT1422_BILLINGSGATE_ON_GOODBODY
A fine woman. Honest as the day is long.

INT1423_BILLINGSGATE_ON_BAGSBY
A decent-enough girl. A little lazy.

INT1424_BILLINGSGATE_ON_MELLORS
He's the gamekeeper. He seems honest enough.

INT1425_BILLINGSGATE_FLATFOOTED_BOOTPRINTS
I've studied all the people here and none of them are flat-footed. It's
a mystery ro me why the bootprints should be flat-footed.

INT1426_BILLINGSGATE_HOBNAILED_BOOTPRINTS
I don't know whose these are.

INT1427_BILLINGSGATE_SLIPPER_PRINTS
I believe the slipper prints are Mr. Coniston's.

INT1428_BILLINGSGATE_MENS_SHOE_PRINTS
The shoe prints are mine.

INT1429_BILLINGSGATE_WOMENS_SHOE_PRINTS
I don't know whose these are.

INT1430_BILLINGSGATE_CHEROOT_IN_POND
As far as I'm aware only the Colonel smoked cheroots. But he was a
most particular man and would never throw a butt into the pond.

INT1501_GOODBODY_EVENTS_YESTERDAY
I have worked here for five years. Last night I cooked and
washed up with Norah. At about 10.30 I heard a loud bang, it gave
me quite a shock. Not long after we went to bed; me and Norah behind
the curtain and Mr. B. on the other side. We had to muck in with Mr.
B. because Sir Redvers had turned up unexpectedly and taken our
room. I was woke up by a shot at 11.20 (according to my clock); the
others was still asleep. I didn't bother 'cos I thought it was poachers.
A few minutes later Mr. Coniston turned up in his dressing gown and
slippers and woke up Mr. B. but I couldn't hear what it was about.

INT1503_GOODBODY_ALIBI
We was all three together, me, Norah and Mr. B. in Mr. B.'s pantry at
10.30 and 11.30. Of course we was asleep at 11.30 so I suppose any of
us could have slipped out without the others noticing.

INT1504_GOODBODY_SLIPPERS
I don't know whose slippers these are.

INT1505_GOODBODY_BOOTS
I remember Billingsgate cleaning boots after dinner but I can't swear
that Sir Redvers' boots were among them. Anyone could have taken
the foots from the kitchen if they came in from the outside door. All
the outside doors are left open since we live in the country.

INT1506_GOODBODY_KNIFE
I used that knife to skin a hare, which explains the blood.

INT1507_GOODBODY_CIGARETTES
I don't smoke. Colonel Darnley smoked cigars.

INT1508_GOODBODY_REVOLVER
I don't know anything about it.

INT1509_GOODBODY_MISSING_STATUE
Mr. B. told me a tramp threw it into the pond. There was a smelly old
villain came by a couple of days ago.

INT1510_GOODBODY_GRAMOPHONE
There is a gramophone in the morning room.

INT1511_GOODBODY_PIANO
There are two pianos, one in the music room and the other in the
morning room.

INT1512_GOODBODY_LADYS_SHOES
I'm not sure. They may be Mrs. Sarah's or Miss Milicent's.

INT1513_GOODBODY_NEWSPAPER
I don't have time to read the paper.

INT1514_GOODBODY_LETTER
I don't know anything about it.

INT1515_GOODBODY_HANDKERCHIEF
Mrs. Sarah and Miss Milicent both have handkerchief's like this one.
I can't say whose it is.

INT1516_GOODBODY_ON_COLONEL_DARNLEY
A hard man both in his business dealings and with his family.

INT1517_GOODBODY_ON_SARAH
Far too young to have married the Colonel and not very happy.

INT1518_GOODBODY_ON_MILICENT
Not a young woman I should want to cross.

INT1519_GOODBODY_ON_CONISTON
What a charmer! I always thought he was after Miss Milicent's
money, but the Colonel obviously didn't.

INT1520_GOODBODY_ON_SLINGSBY
I believe he was very cross with the Colonel about some business
dealings.

INT1521_GOODBODY_ON_BILLINGSGATE
A gentleman. Very loyal to Colonel Darnley.

INT1523_GOODBODY_ON_BAGSBY
A good girl but lazy.

INT1524_GOODBODY_ON_MELLORS
Not a nice man. Not to be trusted. Colonel Darnley talked of giving
him his notice; he'd already given him a warning letter.

INT1525_GOODBODY_FLATFOOTED_BOOTPRINTS
I remember the gardener's child playing around wearing grown-up's
boots. They made flat-footed prints because they were too big for
her.

INT1526_GOODBODY_HOBNAILED_BOOTPRINTS
I don't know whose these are.

INT1527_GOODBODY_SLIPPER_PRINTS
I don't know whose these are.

INT1528_GOODBODY_MENS_SHOE_PRINTS
I don't know whose these are.

INT1529_GOODBODY_WOMENS_SHOE_PRINTS
I don't know whose these are.

INT1530_GOODBODY_CHEROOT_IN_POND
I don't know anything about it.

INT1601_BAGSBY_EVENTS_YESTERDAY
I have worked here for six months and I don't like it. Last night I
helped Mrs. Goodbody to prepare dinner and afterwards I served
coffee in the lounge to Mrs. Sarah and Miss. Milicent. Then I helped
Mrs. G. to wash up whilst Mr. Billingsgate cleaned the boots. Just
before we went to bed there was a loud bang. I thought it was a shot
but Mrs. G. said it was a door banging. Then we went to bed. Mrs. G.
and I had to sleep behind a curtain in the butlers' pantry 'cos Sir
Redvers had come unexpectedly and taken our room. Last thing was
I woke when Mr. Coniston woke Mr. B, but I stayed where I was.

INT1603_BAGSBY_ALIBI
I'm not good where times are concerned. I s'pose I was with Mr. B.
and Mrs. G. in Mr. B.'s room.

INT1604_BAGSBY_SLIPPERS
I don't know whose slippers these are.

INT1605_BAGSBY_BOOTS
Mr. B. cleaned boots after dinner.

INT1606_BAGSBY_KNIFE
I don't know anything about the knife.

INT1607_BAGSBY_CIGARETTES
I don't smoke. Colonel Darnley smoked cigars.

INT1608_BAGSBY_REVOLVER
I don't know anything about it.

INT1609_BAGSBY_MISSING_STATUE
I wasn't aware it was missing.

INT1610_BAGSBY_GRAMOPHONE
There is a gramophone in the morning room.

INT1611_BAGSBY_PIANO
There are two pianos, one in the music room and the other in the
morning room.

INT1612_BAGSBY_LADYS_SHOES
These are Mrs. Sarah's shoes. i don't know when they were last worn.

INT1613_BAGSBY_NEWSPAPER
I don't know anything about it.

INT1614_BAGSBY_LETTER
I don't know anything about it.

INT1615_BAGSBY_HANDKERCHIEF
Both the ladies have this sort of hanky. Sometimes mrs. G. is given
the older ones.

INT1616_BAGSBY_ON_COLONEL_DARNLEY
Very strict. I didn't like him.

INT1617_BAGSBY_ON_SARAH
If you ask me she didn't like the Colonel. He was too old for her.

INT1618_BAGSBY_ON_MILICENT
A determined young woman. It's lucky for the Colonel that he agreed
to less Miss. Milicent marry Mr. Coniston.

INT1619_BAGSBY_ON_CONISTON
A very nice gentleman. I'm suprised the Colonel liked him.

INT1620_BAGSBY_ON_SLINGSBY
I didn't know the gentleman.

INT1621_BAGSBY_ON_BILLINGSGATE
An old fuddy-duddy.

INT1622_BAGSBY_ON_GOODBODY
Very kind to me.

INT1624_BAGSBY_ON_MELLORS
A rough man. A womanizer by all accounts.

INT1625_BAGSBY_FLATFOOTED_BOOTPRINTS
I don't know anything about them.

INT1626_BAGSBY_HOBNAILED_BOOTPRINTS
I don't know anything about them.

INT1627_BAGSBY_SLIPPER_PRINTS
I don't know anything about them.

INT1628_BAGSBY_MENS_SHOE_PRINTS
I don't know anything about them.

INT1629_BAGSBY_WOMENS_SHOE_PRINTS
I don't know anything about them.

INT1630_BAGSBY_CHEROOT_IN_POND
I don't know anything about it.

INT1701_MELLORS_STATEMENT
I have worked for Colonel Darnley for five years. He was strict
but fair. I have no complaints. Last night I did my last rounds at
8.00 pm. I saw nothing suspicious. I spent the rest of the evening at
home and went to bed at 10.00. I didn't hear any strange noises. It
wasn't the weather for poachers.

INT1703_MELLORS_ALIBI
I was in my cottage alone all evening and I don't gave a tinker's
curse if you believe me or not. If you look for my tracks to the big
house. you won't find them.

INT1704_MELLORS_SLIPPERS
I don't give a damn about slippers.

INT1705_MELLORS_BOOTS
Piss off! I'm not showing anyone my boots.

INT1706_MELLORS_KNIFE
I don't know anything about any bloody knife!

INT1707_MELLORS_CIGARETTES
Go to hell! I'm not answering any questions.

INT1708_MELLORS_REVOLVER
I don't own a revolver, I use a shotgun.

INT1709_MELLORS_MISSING_STATUE
Mrs. G. at the big house turned away a tramp. That'd be two days
ago. I caught him lurking about and found the statue in the pond.

INT1710_MELLORS_GRAMOPHONE
I don't know anything about any gramophone.

INT1711_MELLORS_PIANO
I don't know anything about any bloody piano.

INT1712_MELLORS_LADYS_SHOES
Do I look like I wear lady's shoes?

INT1713_MELLORS_NEWSPAPER
I only ever read the racing pages.

INT1714_MELLORS_LETTER
Why should I know anything about some bloody letter?

INT1715_MELLORS_HANDKERCHIEF
Do I look like I use lady's hankys?

INT1716_MELLORS_ON_COLONEL_DARNLEY
I've nothing to say.

INT1717_MELLORS_ON_SARAH
I've nothing to say.

INT1718_MELLORS_ON_MILICENT
I've nothing to say.

INT1719_MELLORS_ON_CONISTON
I've nothing to say.

INT1720_MELLORS_ON_SLINGSBY
I've nothing to say.

INT1721_MELLORS_ON_BILLINGSGATE
I've nothing to say.

INT1722_MELLORS_ON_GOODBODY
I've nothing to say.

INT1723_MELLORS_ON_BAGSBY
I've nothing to say.

INT1725_MELLORS_FLATFOOTED_BOOTPRINTS
Clear off! I'm not showing anyone my boots.

INT1726_MELLORS_HOBNAILED_BOOTPRINTS
Clear off! I'm not showing anyone my boots.

INT1727_MELLORS_SLIPPER_PRINTS
I don't know whose they are.

INT1728_MELLORS_MENS_SHOE_PRINTS
I don't know whose these are.

INT1729_MELLORS_WOMENS_SHOE_PRINTS
Do I look like I wear women's shoes?

INT1730_MELLORS_CHEROOT_IN_POND
I don't know anything about it.
