LOC001_BATHROOM
The bathroom contains an enamelled cast iron bath with claw feet
and a toilet bearing a brass tablet calling it 'The Imperial Avenger'.
A washstand with a marble top and a pedestal washbowl complete
the ensemble. Various toiletries are scattered around in the normal
way.

LOC002_ORCHARD
The park wall lies north and has several pear-trees trained in
espalier against it. There are a large number of apple trees, but no
fruit. There are various marks on the ground, too unclear to be sure
that they are footprints.

LOC003_KITCHEN_GARDEN
The kitchen garden is full of frozen vegetables lying under snow.
Various footprints are visible in the snow.

LOC004_OUTHOUSES
This section of the garden contains various outhouses; a laundry, a
coal store and a pigeon-coop.

LOC005_ORNAMENTAL_POND
An ornamental pond stands at the western end of the terrace.
The pond is covered in ice. In the four corners of the pond are
stone pedestals. These hold statues.

LOC006_TERRACE
From the house a French window leads onto this paved terrace, which
shows traces of many footprints in the snow. The French window is
open and has a broken pane.

LOC007_COLONELS_STUDY
Colonel Darnley's body lies on a turkish carpet in the middle of the
study. A port glass is by his body and a tantalus of port stands on a
table. The room is panelled and contains several club-chairs, some
glass cases holding stuffed birds and a writing table with a letter on
it as well as various sporting magazines and a rack of sporting guns
and pistols. As you walk on the floor by the French window in the
west wall, you feel broken glass underfoot.

LOC008_HALL
The walls of the hall are decorated with swords and Civil War
armour. The floor is marble. The only furniture is a glass case
containing various flints and shards of pottery. At the far end of the
hall, two sets of fine armour stand either side of the stairs which
have barley-sugar banisters and carved pineapple finials.

LOC009_KITCHEN
The kitchen has game birds hanging from the ceiling and the usual
kitchen furniture. On the sink draining-board is a knife. By the
outside door is a line of boots and some cleaning brushes and polish.

LOC010_BUTLERS_PANTRY
The butler's pantry is laid out as a sitting room with a bed behind a
curtain. Two temporary beds have been made up. There is a small
bookshelf.

LOC011_MAZE
Situated on the east side of the house, the maze consists of low
box hedges. The marks in the snow cannot be deciphered into
footprints.

LOC012_WEST_WALK
The gravel path around the house passes between the smooth snow
covered tennis court and a bed of withered flowers covered in snow.
Various footprints are visible in the snow.

LOC013_LOUNGE
The centrepiece of the lounge is a three piece suite on a Chinese
carpet. There are several tables holding magazines and novels
marked with bookmarks. Recent family portraits are on the walls.
The fireplace is carved and holds the remains of a fire. On the
mantlepiece is an Indian rosewood box with an ivory inlay.

LOC014_DINING_ROOM
The dining room holds a fine oak table with chairs in William and
Mary style. A glass case contains various pieces of Delft pottery. A
sideboard holding a silver wine cooler and a pair of Sevres porcelain
urns stand against one wall. The fireplace is of carved marble and
the walls hold various Italian landscapes.

LOC015_MUSIC_ROOM
In the centre of the music room is a piano and, on top, a brass ashtray
with the stub of a cigar in it. There are several chairs, a music stand
and in one corner a large harp with broken strings.

LOC016_BILLIARD_ROOM
A full size table occupies the centre and of the wall a board indicates
the result of a game. There is a small bookcase holding magazines
and several novels by Conan Doyle and Buchan. On top of the book-
case are three wine glasses and an ashtray.

LOC017_DRIVE
From a pair of splendid wrought iron gates the drive runs north
ending in a flight of steps leading up to the principal entrance of the
house, flanked by a pair of stone lions. The snow reveals a mass of
[[red:footprints]].

LOC018_EAST_WALK
This gravel path runs east-west across the front of the house flanked
by an avenue of statues. The snow covered gravel is too rough to
distinguish footprints.

LOC019_SUMMER_HOUSE
A wooden summer house stands on a patch of lawn. Inside can be
seen some croquet mallets and hoops, several cigarette ends and a
handkerchief.

LOC020_WEST_LAWN
Between the summer house and the drive is a lawn. It is planted with
a few saplings and the covering of snow shows footprints.

LOC021_STABLES
The stables are falling into disrepair. One part contains Colonel
Darnley's bay hunter. The other garages a large Daimler. The yard
is full of straw and oil spills, and is crossed by footprints. The tack
room holds the saddle and gear for the horse.

LOC022_EAST_LAWN
An area of lawn between the stables and the cottage. The smooth
covering of snow is broken by footprints.

LOC023_GAMEKEEPERS_COTTAGE
In the damp shade of some chestnut trees is a gamekeeper's cottage
tucked against the south-east corner of the park. The door of the
cottage is open and footprints are visible across the threshold. Inside
are various items of game, two shotguns on the wall, a table covered
by oil cloth, an unmade bed, a slop-stone sink and an open fire with a
pot hanging over it. The place is very dirty; the hearth is littered
with foodscraps, the ends of cigarettes and newspapers.

LOC024_MILLICENT_BEDROOM
Millicent Darnley's bedroom is decorated to a young lady's taste
with a bed, wardrobe, dressing table and a small writing table.
The surfaces are covered with small ornaments, mainly of dogs
and the walls have pictures of favourite pets.

LOC025_LANDING
The landing walls hold some fine antlers and animal heads and some
bad portraits of the Darnley ancestors.

LOC026_SERVANTS_QUARTERS
The servants' quarters consist of a single room with two single beds,
a rail for hanging clothes on behind a curtain, a wash stand and a
chest of drawers. On the chest is a bundle of correspondence and
various framed photographs. A gentleman's country-suit with a
newspaper in the pocket is hanging on the rail amongst the dresses
and a pipe is on the washstand.

LOC027_MASTER_BEDROOM
Colonel and Mrs. Darnley's bedroom is heavily panelled and reflects
the Colonel's tastes, with sporting prints and a humidor of cigars.
There is a double bed, a dressing table, wardrobe and trouser press. A
small bathroom is attached.

LOC028_MORNING_ROOM
The morning room holds a chintz sofa and an occasional table with
magazines and books. Against one wall is a piano. On a table stands
a gramophone. There are various pictures, mainly watercolours of
birds.

LOC029_GUEST_ROOM
A guest-room decorated in blue with wardrobe, bed, washstand and
writing-table. By the bed is a pair of men's slippers. On the writing
table is a pack of cigarettes and some stationary and pens.

LOC030_GRAVEL_WALK
The gravel walk is covered by snow too broken to show the traces of
footprints.

LOC031_SOUTHEAST_CORNER
At the south-east corner of the house is a square of empty lawn. The
smooth cover of snow is broken by footprints.

PER101_COLONEL_DARNLEY
Aged 60. The Colonel served in the South African War and
contracted enteric fever which left him feeling debilitated and short-
tempered. He had only a small inheritance but made a fortune on the
stock exchange. He was free with his tips on the market, but didn't
always follow his own recommendations.

P_SARAH_DARNLEY
Colonel Darnley's wife. Aged 27. Fair-haired, beautiful and
sophisticated. She wears a morning dress and shows signs of tired-
ness and stress.

P_MILLICENT_DARNLEY
Colonel Darnley's daughter. Aged 23. Well-dressed but rather plain.
Cool and determined looking. She wears a blouse and skirt.

P_ARTHUR_CONISTON
Millicent Darnley's fiance. Aged 25. Average height and very good
looking. His manner is honest and friendly. He dresses fashionably
and wears black patent shoes.

P_REDVERS_SLINGSBY
Friend of the deceased. Aged 52. Very tall and bony with side
whiskers and a red face. Wears country-tweeds and boots. His
manner is ill-tempered.

P_ARNOLD_BILLINGSGATE
The Butler. Aged about 60; gentlemanly manners; bald and thin;
average height. Wears a tail coat and ordinary men's shoes.

P_MILDRED_GOODBODY
The Cook. Aged 55. Pleasant-faced. Cheerful. Overweight.

P_NORAH_BAGSBY
The Housemaid. Aged 19. Small pale girl who sniffs a lot. Wears a
maid's uniform.

P_RONALD_MELLORS
The Gamekeeper. Stocky, black curly hair, good looking, surly-
looking. Wears working clothes and hob-nailed boots. Age 35.

OBJ201_POND
Near the centre of the pond the ice is thinner as if it has frozen again
after having been broken. Beneath the ice you can see the missing
statue from the fourth pedestal.

OBJ202_SUNKEN_STATUE
The statue that is beneath the ice is the same as those on the
pedestals. Stuck in a crevice of the statue is the soaked butt of a
cheroot.

OBJ203_REVOLVER
The revolver found in the hall is a Webley-Fosbery .455 service
revolver. One bullet has been discharged from it.

OBJ204_STATUES
The statues form a set of four, representing the Four Seasons. They
are of Italian marble and rest on their own weight rather than being
cemented to their plinths. Some strength would be required to move
one.

OBJ205_FOOTPRINTS_POND
Only one set of footprints can be made out in the snow. They are of
flat footed bootprints coming to and from the terrace.

OBJ206_SLIPPERS
The slippers are slightly damp and stained with mud.

OBJ207_CIGARETTES
These cigarettes are an expensive brand by Tribourg & Freyer.

OBJ208_KNIFE
This kitchen knife is stained with blood.

OBJ209_BOOTS
All these boots are polished clean except for a mud stained pair that
apparently belong to Sir Redvers Slingsby.

OBJ212_FOOTPRINTS_KG
Both flat footed boot prints and slipper prints can be seen going
between the kitchen and the maze.

OBJ213_BED_MASTER
This double bed has not been slept in.

OBJ214_WARDROBE
As well as clothes the wardrobe contains a selection of
men's and women's shoes.

OBJ215_CIGARS
The cigars are Burmah cheroots.

OBJ216_DRESSING_TABLE
There is nothing of note on the dressing table.

OBJ217_SHOES
This selection of mens and womens shoes is unremarkable. One set of
lady's shoes is mud-stained.

OBJ219_CORRESPONDENCE
These letters are all from Mrs. Goodbody's nephew.

OBJ220_PHOTOGRAPHS
These photographs depict Mrs. Goodbody's various ugly relatives.

OBJ221_SUIT
This gentleman's country-suit is apparently Sir Redvers'.

OBJ222_NEWSPAPER
One headline on the front page catches your eye -
'Collapse of Rio Plata Mining Co. - Our co-respondent in Lima, Peru
reports the collapse of several silver mining companies through the
fraud of their directors. These frauds are expected to cause heavy
loss to British investors.'

OBJ223_PIPE
The pipe is in the style called 'calabash' with a meerschaum bowl and
amber mouthpiece.

OBJ224_BOOKSHELF
The bookshelf contains books on self-improvement and domestic
accounts.

OBJ225_FRENCH_WINDOW_TERRACE
One of the panes is smashed, but there is no glass on the terrace. The
window lock shows that it cannot be locked or unlocked from outside.

OBJ226_FOOTPRINTS_TERRACE
A mess of footprints including boots, slippers and some shoe prints.

P_THE_BODY
The body is dressed in a smoking jacket open at the chest. There is a
bloody bullet wound in the front of his dress-shirt. The bullet has not
passed through the body. Evidently the Colonel had got out of his
chair on hearing or seeing his murderer. The impact of the bullet had
caused him to spin and fall and the furniture had got in the way,
further deflecting the body. It is no longer possible to tell the
direction of the shot.

OBJ228_PORT_GLASS
The port glass is one of a set engraved with the words 'Floreat
Darnley'. A crust of dried liquid is at the bottom and lip marks on the
rim though no trace of lipstick.

OBJ229_TANTALUS
The tantalus is made of cherrywood. It holds an empty decanter
with a silver label marked 'Brandy' and a half full decanter marked
'Port'. The decanters are normally inaccessible since they are held in
place by a sort of 'lid' of wood which is fastened by a small lock. The
key is in the lock.

OBJ230_LETTER
The letter is an incomplete draft : 'Dear Sir, I have considered your
monstrous suggestion and find I cannot....'

OBJ231_GUN_RACK
One of the pistols is missing from this rack.

OBJ232_FRENCH_WINDOW_STUDY
One pane is smashed. The glass on the floor is apparently from this.

OBJ233_SHATTERED_GLASS
This glass is apparently from the smashed French window.

OBJ234_GRAMOPHONE
It has a device for playing several records in sequence. All the
records are Chopin.

OBJ235_PIANO_MORNING
There are several sheets of Schubert Lied music on the piano's music
stand.

OBJ236_DISPLAY_CASE
According to a label at the front of the case these flints and shards of
pottery were found in the grounds of the house.

OBJ237_FOOTPRINTS_WW
There are slipper prints, flat-footed boot prints and some shoe prints
heading to and from the terrace and the front of the house.

OBJ238_CIGAR_STUB
This cigar stub is a straight dark cylinder rather than the
conventional shape. That and the tarry appearance suggests a
cheroot.

OBJ239_PIANO_MUSIC
The sheets of music on the piano are for duets.

OBJ240_WINE_GLASSES
The three wine glasses are all dirty.

OBJ241_ASHTRAY
The ashtray contains the remains of three cigars, one Havana and
two cheroots.

OBJ243_FOOTPRINTS_DRIVE
The prints from flat footed boots go east and west along the gravel
path in front of the house. Slipper prints come from the house and
head east and west along the path. Prints from men's shoes come
from the house and go west. Prints from lady's shoes head to and
from the front door and the west lawn. At the gate end of the drive
the prints from men's hobnailed boots go between the west lawn and
the stables.

OBJ244_FOOTPRINTS_EW
The prints from flat footed boots and men's slippers are visible in the
snow heading around the corner of the house, to and from the maze
and avenue of statues.

OBJ245_CIGARETTE_ENDS_SH
These cigarette ends come from a cheap, mass produced brand.

OBJ246_HANDKERCHIEF
This is a lady's hanky, plain lace edged and perfumed.

OBJ247_FOOTPRINTS_WL
Prints from lady's shoes and men's hob-nailed boots can be seen in the
snow going between the drive and the summer house.

OBJ248_FOOTPRINTS_ST
The prints from hob-nailed boots can be seen in the snow going
between the drive and the east lawn.

OBJ249_FOOTPRINTS_EL
The prints from hob-nailed boots can be seen in the snow going east
to west between the stables and the cottage.

OBJ250_CIGARETTE_ENDS_GC
These cigarette ends come from a cheap, mass produced brand.

OBJ251_ARMOUR
A suit of Civil War three-quarter armour with a closed helmet.
Examination discovers a revolver concealed in the helmet.

OBJ252_DOOR_MAT
The doormat is made of coarse coir and bears the word 'WELCOME' in faded
letters. It is damp with recent use.

WHAT_REALLY_HAPPENED
What really happened at Darnley Park?@
@
On the morning of the murder Arthur Coniston, the boy-friend of
Millicent Darnley, arrived by arrangement to ask Colonel Darnley for
permission to marry his daughter. This conversation took place
during the afternoon and Colonel Darnley refused the request.
Although he found Coniston amusing, he felt that his visitor was
after Millicent's inheritance. Coniston, now resolved upon murder,
quietly informing the other members of the household that the
Colonel had agreed to the marriage. He was unaware that the Colonel
had decided to write him a letter confirming his rejection. During the
afternoon an unexpected visitor arrived, Sir Redvers Slingsby who
had invested in Peruvian mining shares on the advice of his friend
Colonel Darnley. In the morning's papers was news of the collapse of
these shares. Angry with his friend, Slingsby had rushed down to
Darnley Park to ask the Colonel to lend him money to avoid ruin.@
@
Dinner that evening finished at 9.00. Millicent and Sarah retired
to the lounge for coffee while the men drank port and played
billiards. At 9.30 the gentlemen joined the ladies while the
servants ate in the kitchen. The atmosphere was tense since
Slingsby had not had opportunity to raise his problems. At 10.00 that
night impatience got the better of him and he drew Darnley to the
study whilst Coniston and Millicent went to the music room to sing
duets. For half an hour Slingsby and the Colonel quarrelled (at this
time Billingsgate was cleaning boots in the kitchen) and at 10.30
Slingsby stormed out of the study by the hall door, slamming it
furiously. This noise was interpreted by some as a shot. The
slamming of the door underlined the generally tense atmosphere.
The ladies went upstairs but Arthur Coniston stayed in the music
room smoking a cheroot and considering his plan. He was unaware
that Sarah had plans of her own.@
@
Sarah Darnley was unhappy with her husband and having an
affair with Mellors, the gamekeeper. She had arranged to meet
Mellors at the summer house at 10.45. Mellors was there, waiting and
smoking cigarettes. Sarah took steps to keep the affair secret and to
maintain to Millicent the pretence that she was in the house, she told
her of her intention to play on the morning room piano. In truth she
played a series of gramophone records which Millicent heard from her
room. It was not necessary for her to take account of Colonel Darnley
since experience had taught her that the Colonel would lock himself
in his study and get drunk on such an occasion as this. Sarah next
left the house and went down to the summer house where she met
Mellors.@
@
Leaving the music room, Coniston tried the study door and finding
it locked, guessed what was happening and devised his plan. He had
stolen a gun from the study earlier in the day. He now changed into
dressing gown and slippers and went outside the house and around to
the kitchen door which was open. Reaching through the door he
picked up Sir Redvers Slingsby's boots. Changing into them he walked
around the house to the terrace. The boots being too large, they left
flat-footed bootprints. From the terrace Coniston looked into the
study where the Colonel was drinking. He tapped on the window, the
Colonel stood up and saw him, Coniston fired the gun and the Colonel
fell dead. He now had to act fast to dispose of the gun, disguise of the
fact of the bullet-hole in the window glass and return the boots. He
broke the ice on the pond with a statue taken from one of the
pedestals and threw the gun into the water. He then returned to the
kitchen, changed the boots for the slippers and then entered the
house by the front door. He did not notice Sarah who had heard the
shot and rushed back before everyone was roused by the noise and
she was discovered. In her haste Sarah dropped a handkerchief in
the summer house.@
@
Coniston now came to the boldest part of his plot. He woke
Billingsgate and persuaded him to break in by the French window
instead of searching for his keys. Coniston took care to reach the
patio before his companion and threw a stone through the same pane
of glass that bore the bullet-hole from the fatal shot, thus
obliterating the evidence of where the shooting took place. He
then invited Billingsgate to open the window and confirm that it had
been locked. He also told the Butler that he intended to follow the
murderer's bootprints which were clear in the snow. The object of
this move was to provide an explanation of the trail already left by
his slippers when he first stole and returned the boots.@
@
Various minor clues led towards Coniston as the murderer, but one
was fatal to him. It was evident that the murderer had worn the
boots and returned them to the kitchen. How then had the murderer
left the kitchen in his or her own footwear? There were only two
possibilities : the murderer had left via the butler's pantry or the
outside door. The former was impossible since three people were
occupying the pantry of whom at least one (Mrs. Goodbody) had been
wakened by the shot and would have heard any stranger entering the
room. The second was possible but the murderer would leave the foot-
prints of his ordinary footwear. Other than the boots, there were
prints only from Arthur Coniston's slippers. Coniston's explanation
that he had left these prints in following the murderers boot-trail
would not hold water. The murderer had to leave footprints in two
sets of footwear. Coniston's slippers were the only other set.

SEALED_ROOM_INTRO
You have been summoned to Darnley Park one winter's day to
investigate the murder of Colonel Sebastian Darnley at some time
the previous evening.@
@
The suspects are:@
  Sarah Darnley - the deceased's wife@
  Millicent Darnley - the deceased's daughter@
  Arthur Coniston - fiance of Millicent@
  Sir Redvers Slingsby - friend of the deceased@
  Arnold Billingsgate - butler@
  Mildred Goodbody - cook@
  Norah Bagsby - housemaid@
  Ronald Mellors - gamekeeper@
@
You are free to search the house and grounds and to question the
suspects. Examination of the scene and skillful interrogation will
yield sufficient information to solve the mystery. And mystery it is!
The body of Colonel Darnley was found in his study, the doors and
window of which were all locked from the inside. The only keys were
in the possession of the Colonel and his faithful butler. How could
the sealed-room murder be committed?

Q_1
Who smoked cigarettes in the summer house?

Q_2
Who dropped the handkerchief in the summer house?

Q_3
What was the source of the music in the morning room?

Q_4
Where did the murderer hide the gun?

Q_5
When did the murder occur? (type letter)@
 a) 10:05 - 10:35 pm@
 b) 10:35 - 11:05 pm@
 c) 11:05 - 11:35 pm@
 d) 11:35 - 12:05 am@
 e) 12:05 - 12:35 am

Q_6
Which door did the murderer leave the kitchen by?

Q_7
Why were the murderer's bootprints flat-footed?

Q_8
What caused the first bang that was heard?

Q_9
Where was the murderer when the shot was fired?

Q_10
Who was the letter written by Colonel Darnley for?

Q_11
What was the motive for the murder?

Q_12
How did the murderer hide the bullet hole in the window?

Q_13
Who was the murderer?

CONGRATULATIONS
Congratulations Inspector. With your evidence Arthur Coniston is arrested,
tried and found guilty of the murder of Colonel Sebastian Darnley. He is
sentenced to 30 years of imprisonment at her majesty's pleasure.
