events yesterday murder
"I have worked here for five years. Last night I cooked and washed up
with Norah. At about 10.30 I heard a loud bang, it gave me quite a
shock. Not long after we went to bed; me and Norah behind the curtain
and Mr. B. on the other side. We had to muck in with Mr. B. because
Sir Redvers had turned up unexpectedly and taken our room.@
@
I was woken up by a shot at 11.20 (according to my clock); the others
were still asleep. I didn't bother 'cos I thought it was poachers. A few
minutes later Mr. Coniston turned up in his dressing gown and slippers
and woke up Mr. B., but I couldn't hear what it was about."

alibi
"We was all three together, me, Norah and Mr. B. in Mr. B.'s pantry
at 10.30 and 11.30. Of course we was asleep at 11.30 so I suppose
any of us could have slipped out without the others noticing."

slippers
"I don't know whose slippers these are."

boots
"I remember Billingsgate cleaning boots after dinner but I can't
swear that Sir Redvers' boots were among them. Anyone could have
taken the boots from the kitchen if they came in from the outside
door. All the outside doors are left open since we live in the
country."

knife
"I used that knife to skin a hare, which explains the blood."

cigarettes
"I don't smoke. Colonel Darnley smoked cigars."

missing statue
"Mr. B. told me a tramp threw it into the pond. There was a smelly
old villain came by a couple of days ago."

gramophone
"There is a gramophone in the morning room."

piano
"There are two pianos, one in the music room and the other in the
morning room."

ladys shoes
"I'm not sure. They may be Mrs. Sarah's or Miss Millicent's."

newspaper
"I don't have time to read the paper."

handkerchief
"Mrs. Sarah and Miss Millicent both have handkerchiefs like this one.
I can't say whose it is."

colonel darnley
"A hard man both in his business dealings and with his family."

sarah
"Far too young to have married the Colonel and not very happy."

millicent
"Not a young woman I should want to cross."

arthur coniston
"What a charmer! I always thought he was after Miss Millicent's
money, but the Colonel obviously didn't."

redvers slingsby
"I believe he was very cross with the Colonel about some business
dealings."

arnold billingsgate
"A gentleman. Very loyal to Colonel Darnley."

norah bagsby
"A good girl but lazy."

ronald mellors
"Not a nice man. Not to be trusted. Colonel Darnley talked of giving
him his notice; he'd already given him a warning letter."

flatfooted bootprints
"I remember the gardener's child playing around wearing grown-up's
boots. They made flat-footed prints because they were too big for
her."

hobnailed bootprints
"I don't know whose these are."

slipper prints
"I don't know whose these are."

mens shoe prints
"I don't know whose these are."

womens shoe prints
"I don't know whose these are."

*
"I'm afraid you're asking the wrong person, dear."
