events of yesterday
Father was a difficult man to live with but I never expected - this!
Last night we all ate together until coffee which Sarah and I took
together in the lounge. The men joined us later for half an hour,
then Arthur and I went into the music room where we talked for a
while and played duets on the piano. At about 10.30 I decided to go
to bed. I know the time because I looked at my watch when there was
a loud noise - probably a poacher somewhere. Arthur stayed in the
billiard room and I went upstairs. I think I saw Sir Redvers
disappearing into his bedroom, but I was distracted by Sarah who was
on the landing. She said she was intending to play the piano in the
morning room and hoped it would't disturb me. I went to my room and
stayed there. I heard Sarah playing the piano then drifted off to
sleep. I woke up at about 11.20 by the bedside clock and heard Sarah
still playing a Chopin nocturne. She seemed to be having trouble
since the same part was being repeated over and over again. I went
to sleep for a few more minutes when there was a bang - a door
slamming, I thought. Then at about midnight there was a racket of
people everywhere. I went into Sarah's room and found her
undressing there. We went into the morning room and found
Billingsgate waking Sir Redvers.

alibi
I was with Arthur in the music room at 10.30 and, naturally, I was
alone in bed at 11.30.

slippers
I don't know whose slippers these are.

boots
I don't know anything about these boots.

knife
I don't know anything about the knife.

cigarettes
I don't smoke. My father smoked cigars.

service revolver
I don't recognise it.

missing statue
Someone - I forget who - told me that a beggar had pushed it into
the pond. Out of spite I suppose.

gramophone
We have a gramophone in the morning room.

piano
Which piano? Arthur and I played duets on the music room piano for a
while after dinner. I remember that later, Sarah said she intended
to play the morning room piano. I woke up at about 11.20 and heard
Sarah still playing a Chopin nocturne. She was having difficulty and
repeated the same piece again and again.

ladys shoes
They aren't my shoes.

newspaper
I don't read the newspaper frequently.

letter
I don't know anything about this letter.

handkerchief
I'm always losing handkerchiefs so I suppose it could be mine. I
don't remember when I lose them. I certainly wasn't in the summer
house yesterday. Is it important?

colonel darnley
Daddy was a tyrant but always kind to me. He was always fearful that
Sarah would leaver him for a younger man.

sarah darnley
We got on well enough though it is difficult to have a step-mother
who is almost the same age. I thought she would leave daddy some day
as soon as she found a lover. But, of course, she would need Daddy's
money.

arthur coniston
He's a darling! I don't know how he persuaded daddy to agree, so I
am probably mistaken.

sir redvers slingsby
I didn't know him before last night.

arnold billingsgate
A decent old fellow.

mildred goodbody
An old dear.

norah bagsby
A clumsy girl.

ronald mellors
Furtive. I don't like the way he looks at my step-mother. I advised
Daddy to get rid of him.

flatfooted bootprints
Oh really, it's too silly to ask me to recognise footprints.

hobnailed bootprints
Oh really, it's too silly to ask me to recognise footprints.

slipper prints
Oh really, it's too silly to ask me to recognise footprints.

mens shoe prints
Oh really, it's too silly to ask me to recognise footprints.

womens shoe prints
Oh really, it's too silly to ask me to recognise footprints.

cheroot in the pond
I don't know anything about it.
