events of yesterday
I have worked here for six months and I don't like it. Last night I
helped Mrs. Goodbody to prepare dinner and afterwards I served
coffee in the lounge to Mrs. Sarah and Miss. Milicent. Then I helped
Mrs. G. to wash up whilst Mr. Billingsgate cleaned the boots. Just
before we went to bed there was a loud bang. I thought it was a shot
but Mrs. G. said it was a door banging. Then we went to bed. Mrs. G.
and I had to sleep behind a curtain in the butlers' pantry 'cos Sir
Redvers had come unexpectedly and taken our room. Last thing was I
woke when Mr. Coniston woke Mr. B, but I stayed where I was.

alibi
I'm not good where times are concerned. I s'pose I was with Mr. B.
and Mrs. G. in Mr. B.'s room.

slippers
I don't know whose slippers these are.

boots
Mr. B. cleaned boots after dinner.

knife
I don't know anything about the knife.

cigarettes
I don't smoke. Colonel Darnley smoked cigars.

service revolver
I don't know anything about it.

missing statue
I wasn't aware it was missing.

gramophone
There is a gramophone in the morning room.

piano
There are two pianos, one in the music room and the other in the
morning room.

ladys shoes
These are Mrs. Sarah's shoes. i don't know when they were last worn.

newspaper
I don't know anything about it.

letter
I don't know anything about it.

handkerchief
Both the ladies have this sort of hanky. Sometimes mrs. G. is given
the older ones.

colonel darnley
Very strict. I didn't like him.

sarah darnley
If you ask me she didn't like the Colonel. He was too old for her.

milicent darnley
A determined young woman. It's lucky for the Colonel that he agreed
to less Miss. Milicent marry Mr. Coniston.

arthur coniston
A very nice gentleman. I'm suprised the Colonel liked him.

sir redvers slingsby
I didn't know the gentleman.

arnold billingsgate
An old fuddy-duddy.

mildred goodbody
Very kind to me.

ronald mellors
A rough man. A womanizer by all accounts.

flatfooted bootprints
I don't know anything about them.

hobnailed bootprints
I don't know anything about them.

slipper prints
I don't know anything about them.

mens shoe prints
I don't know anything about them.

womens shoe prints
I don't know anything about them.

cheroot in the pond
I don't know anything about it.
