QUESTION_1
Who smoked cigarettes in the summer house?
ronald | mellors
 
QUESTION_2
Who dropped the handkerchief in the summer house?
sarah
 
QUESTION_3
What was the source of the music in the morning room?
gramophone | record player
 
QUESTION_4
Where did the murderer hide the gun?
armour | hall
 
QUESTION_5
When did the murder occur?
11:05 | 11:35
 
QUESTION_6
Which door did the murderer leave the kitchen by?
garden
 
QUESTION_7
Why were the murderers bootprints flat-footed?
big | large
 
QUESTION_8
What caused the first bang that was heard?
door | slam
 
QUESTION_9
Where was the murderer when the shot was fired?
terrace
 
QUESTION_10
Who was the letter written by Colonel Darnley for?
arthur | coniston
 
QUESTION_11
What was the motive for the murder?
marry milicent
 
QUESTION_12
How did the murderer hide the bullet hole in the window?
stone | rock
 
QUESTION_13
Who was the murderer?
arthur | coniston
