events yesterday murder
I have known Darnley for about 20 years. It was some confidential
business dealings that brought me here urgently yesterday. Last
night I had dinner with the family and young Coniston. Afterwards
- at about 9.00 - we gentlemen had a game and some port in the
billiard room, then we joined the ladies in the lounge for half
an hour.@
@
Darnley and I left the others at 10.00 and chatted about our
business for a while. The discussion was very friendly and I left
Darnley alive at 10.30.@
@
I was sleeping in the servants' quarters and went to bed straight
away. Having had a bit to drink I slept very soundly and heard
nothing until Billingsgate woke me at midnight to tell me about
this terrible business.

alibi
I left Darnley alive at 10.30 and it's damn nonsense to suggest I
shot him with all the house awake and then waited to see what would
happen. At 11.30 I was asleep like a good Christian, and the Devil
take you if a fellow needs an alibi!

boots
These are certainly my boots. I last wore them yesterday afternoon
and put them out for Billingsgate to clean. I certainly didn't wear
them after dinner and can't explain who may have. I suppose that, if
the staff were asleep, someone could have sneaked into the kitchen
and taken them.

cigarettes
I smoke a pipe and the occasional Havana cigar. My pipe is in my
room.

service revolver
I don't recognise it.

gramophone
The Darnley's have a gramophone in the morning room.

piano
The Darnley's have two pianos, one in the music room and one in the
morning room.

newspaper
I was reading it on the train coming here. Some of my friends lost
money in the collapse.

letter
The letter certainly wasn't addressed to me. Darnley would have
called me by name, not 'Dear Sir' - after all we were friends.

colonel darnley
A hard man but very fair. Once I had explained my business problem
he agreed to help me out.

sarah
Darnley should never have married her. I told him so at the time but he wouldn't
hear of it. She's half his age and twice as clever. A man in Darnley's position
needs a wife who knows her place, not one who is always looking for something
better. I shouldn't wonder if she had her eye on someone else entirely.

millicent
A charming young lady. Spoiled by her father. Personally I
shouldn't like to get on her wrong side.

arthur coniston
Last night was the first time I met him but he seemed a decent
fellow.

arnold billingsgate
I barely know the man.

mildred goodbody
I don't know the woman.

norah bagsby
I don't know the girl.

ronald mellors
I don't know the man.

flatfooted bootprints
The bootprints around the house look like mine, but I didn't make
them. I'm not flat-footed.

cheroot in the pond
A cheroot? Not me, old man! I'm one for Havanas if I'm not smoking
the old pipe.

*
"No idea whatsoever. Can we stick to the point?"
