events yesterday murder
I have worked for Colonel Darnley for five years. He was strict but
fair. I have no complaints. Last night I did my last rounds at 8.00
pm. I saw nothing suspicious. I spent the rest of the evening at
home and went to bed at 10.00. I didn't hear any strange noises. It
wasn't the weather for poachers.

alibi
I was in my cottage alone all evening and I don't give a tinker's
curse if you believe me or not. If you look for my tracks to the big
house, you won't find them.

slippers
I don't give a damn about slippers.

boots
Piss off! I'm not showing anyone my boots.

knife
I don't know anything about any bloody knife!

cigarettes
I smoke cheap cigarettes. What of it? There's no law against it.

service revolver
I don't own a revolver, I use a shotgun.

missing statue
Mrs. G. at the big house turned away a tramp. That'd be two days
ago. I caught him lurking about and found the statue in the pond.

gramophone
I don't know anything about any gramophone.

piano
I don't know anything about any bloody piano.

ladys shoes
Do I look like I wear lady's shoes?

newspaper
I only ever read the racing pages.

letter
Why should I know anything about some bloody letter?

handkerchief
Do I look like I use lady's hankies?

colonel darnley
Strict but fair. I've said all I'm goin to say about him.

sarah
Mrs. Darnely is a fine woman. That's all I'm saying.

millicent
Miss Darnley never had much to do with me. Suited us both.

arthur coniston
I didn't like the look of him. Too smooth by half.

redvers slingsby
Bad-tempered old so-and-so. Came roaring up the drive yesterday afternoon like
he owned the place.

arnold billingsgate
Nosy old devil. Always watching.

mildred goodbody
Mrs. G. minds her own business. I'll say that for her.

norah bagsby
Silly girl. Always giggling.

flatfooted bootprints
Clear off! I'm not showing anyone my boots.

hobnailed bootprints
Clear off! I'm not showing anyone my boots.

slipper prints
I don't know whose they are.

mens shoe prints
I don't know whose these are.

womens shoe prints
Do I look like I wear women's shoes?

cheroot in the pond
I don't know anything about it.

*
"Do I look like I'd know anything about that?"
