ronald mellors statement
I have worked for Colonel Darnley for five years. He was strict but
fair. I have no complaints. Last night I did my last rounds at 8.00
pm. I saw nothing suspicious. I spent the rest of the evening at
home and went to bed at 10.00. I didn't hear any strange noises. It
wasn't the weather for poachers.

alibi
I was in my cottage alone all evening and I don't gave a tinker's
curse if you believe me or not. If you look for my tracks to the big
house. you won't find them.

slippers
I don't give a damn about slippers.

boots
Piss off! I'm not showing anyone my boots.

knife
I don't know anything about any bloody knife!

cigarettes
Go to hell! I'm not answering any questions.

service revolver
I don't own a revolver, I use a shotgun.

missing statue
Mrs. G. at the big house turned away a tramp. That'd be two days
ago. I caught him lurking about and found the statue in the pond.

gramophone
I don't know anything about any gramophone.

piano
I don't know anything about any bloody piano.

ladys shoes
Do I look like I wear lady's shoes?

newspaper
I only ever read the racing pages.

letter
Why should I know anything about some bloody letter?

handkerchief
Do I look like I use lady's hankys?

colonel darnley
I've nothing to say.

sarah darnley
I've nothing to say.

milicent darnley
I've nothing to say.

arthur coniston
I've nothing to say.

sir redvers slingsby
I've nothing to say.

arnold billingsgate
I've nothing to say.

mildred goodbody
I've nothing to say.

norah bagsby
I've nothing to say.

flatfooted bootprints
Clear off! I'm not showing anyone my boots.

hobnailed bootprints
Clear off! I'm not showing anyone my boots.

slipper prints
I don't know whose they are.

mens shoe prints
I don't know whose these are.

womens shoe prints
Do I look like I wear women's shoes?

cheroot in the pond
I don't know anything about it.
