events of yesterday
I married Sebastian two years ago. I am more than twenty years
younger than he - really not much older than Milicent. We have been
very happy together. Last night we all had dinner together. After-
wards the men played billiards while Milicent and I had coffee in
the lounge. At about 9.30 the men joined us for half an hour then
Arthur and Milicent said that they were going to the music room.
Sebastian and Sir Redvers had business to talk about so they went
into the study. I heard them quarelling but couldn't tell what
about. Next there was a loud noise which I took to be Sir Redvers
leaving the study by the door to the hall and banging the door. I
stayed in the lounge for ten minutes and then went upstairs where I
ran into Milicent on the landing. She said that she had left Arthur
in the billiard room and was going to bed. I went into the morning
room and played some Chopin nocturnes on the piano there until about
11.30 when I heard a noise like a shot which I thought was
poachers. Looking at my watch I decided it was time to go to bed. I
was getting changed when I heard Billingsgate rush upstairs to wake
Sir Redvers. Milicent heard the racket and came into my room from
hers. And the rest you know.

alibi
At 10.30 I was reading and drinking coffee in the lounge - on my
own, I'm afraid. At 11.30 I was playing the piano in the morning
room - also alone, alas! I don't suppose it looks to good?

slippers
I don't know whose slippers these are.

boots
I don't know anything about them.

knife
I don't know anything about the knife.

cigarettes
I can't imagine why you are asking me this question. Arthur
Coniston smokes cigarettes.

service revolver
I don't recognise it.

missing statue
I believe a rather nasty tramp, who called two days ago threw it
into the pond.

gramophone
The gramophone? I was in the morning room from about 10.40 until
11.30 playing the piano. It's possible I played a record, but I
don't remember doing so.

piano
If you mean the morning room piano, I was playing it from about
10.40 until I heard the bang at 11.30. I was on my own throughout
and no-one else came into the room.

ladys shoes
Yes, these are my shoes, but I don't recall when I last wore them. I
have no idea why they should be damp - possibly I had them on
earlier yesterday.

newspaper
I believe that Sebastian advised one or two people to invest in
Peruvian shares.

letter
My husband said something to me about having to write a letter. I
understood it was for Arthur - or was it Sir Redvers? Afterwards
Arthur told me that Sebastian had agreed to the marriage, and
Redvers said that he and Sebastian had sorted out their business; so
I'm at a loss about the letter.

handkerchief
You found it in the summer house? I'm absolutely sure it isn't mine.

colonel darnley
He was somewhat strict and suspicous by nature, but we were happy
enough.

milicent darnley
Her father spoiled her so she got used to having her own way.
Sebastian probably agreed to Arthur Coniston's proposal for fear of
what Milicent would do if he refused. I can't see him crossing
Milicent on a matter like that.

arthur coniston
A charmer. I was suspicous of his motives for marrying Milicent, but
Arthur said that when he asked Sebastian my husband agreed, so I am
probably mistaken.

sir redvers slingsby
I felt he had some sort of grudge against Sebastian.

arnold billingsgate
Very honest and loyal.

mildred goodbody
A gossip.

norah bagsby
Lazy.

ronald mellors
A very loyal gamekeeper.

flatfooted bootprints
I'm too distressed to talk about this.

hobnailed bootprints
I'm too distressed to talk about this.

slipper prints
I'm too distressed to talk about this.

mens shoe prints
I'm too distressed to talk about this.

womens shoe prints
I'm too distressed to talk about this.

cheroot in the pond
I don't know anything about it.
