events yesterday murder
"I married Sebastian two years ago. I am more than twenty years
younger than he - really not much older than Millicent. We have
been very happy together. Last night we all had dinner together.
Afterwards the men played billiards while Millicent and I had
coffee in the lounge.@
@
At about 9.30 the men joined us for half an hour then Arthur and
Millicent said that they were going to the music room. Sebastian
and Sir Redvers had business to talk about so they went into the
study. I heard them quarrelling but couldn't tell what about.
Next there was a loud noise which I took to be Sir Redvers leaving
the study by the door to the hall and banging the door. I stayed
in the lounge for ten minutes and then went upstairs where I ran
into Millicent on the landing. She said that she had left Arthur
in the music room and was going to bed.@
@
I went into the morning room and played some Chopin nocturnes on
the piano there until about 11.30 when I heard a noise like a shot
which I thought was poachers. Looking at my watch I decided it was
time to go to bed.@
@
I was getting changed when I heard Billingsgate rush upstairs to
wake Sir Redvers. Millicent heard the racket and came into my room
from hers. And the rest you know."

alibi
"At 10.30 I was reading and drinking coffee in the lounge - on my
own, I'm afraid. At 11.30 I was playing the piano in the morning
room - also alone, alas! I don't suppose it looks to good?"

cigarettes
"I can't imagine why you are asking me this question. Arthur
Coniston smokes cigarettes."

missing statue
"I believe a rather nasty tramp, who called two days ago threw it
into the pond."

gramophone
"The gramophone? I was in the morning room from about 10.40 until
11.30 playing the piano. It's possible I played a record, but I
don't remember doing so."

piano
"If you mean the morning room piano, I was playing it from about
10.40 until I heard the bang at 11.30. I was on my own throughout
and no-one else came into the room."

ladys shoes
"Yes, these are my shoes, but I don't recall when I last wore them. I
have no idea why they should be damp - possibly I had them on
earlier yesterday."

newspaper
"I believe that Sebastian advised one or two people to invest in
Peruvian shares."

letter
"My husband said something to me about having to write a letter. I
understood it was for Arthur - or was it Sir Redvers? Afterwards
Arthur told me that Sebastian had agreed to the marriage, and
Redvers said that he and Sebastian had sorted out their business; so
I'm at a loss about the letter."

handkerchief
"You found it in the summer house? I'm absolutely sure it isn't mine."

colonel darnley
"He was somewhat strict and suspicious by nature, but we were happy
enough."

millicent
"Her father spoiled her so she got used to having her own way.
Sebastian probably agreed to Arthur Coniston's proposal for fear of
what Millicent would do if he refused. I can't see him crossing
Millicent on a matter like that."

arthur coniston
"A charmer. I was suspicious of his motives for marrying Millicent, but
Arthur said that when he asked Sebastian my husband agreed, so I am
probably mistaken."

redvers slingsby
"I felt he had some sort of grudge against Sebastian."

arnold billingsgate
"Very honest and loyal."

mildred goodbody
"A gossip."

norah bagsby
"Lazy."

ronald mellors
"A very loyal gamekeeper."

flatfooted bootprints
"I'm too distressed to think clearly about bootprints, I'm afraid."

hobnailed bootprints
"I really couldn't say. I wasn't paying attention to people's boots."

slipper prints
"I don't know whose slippers those would be. I'm sorry, this is all rather too
much."

mens shoe prints
"I'm afraid I don't notice that sort of thing at the best of times."

womens shoe prints
"I couldn't say whose they are. I'm really not in a fit state to be asked about
footprints."

cheroot in the pond
"I don't know anything about it."

*
"I'm afraid I really couldn't say. This has all been such a terrible shock."
